// ============================================================
// mockData.js additions — DEMO fallback for Environment 360
// ============================================================
export const envOverview = () => ({
  kpis: { monitored: 9, healthy: 6, degraded: 2, failed: 1,
    certs_total: 5, certs_7d: 1, certs_30d: 3 },
  critical_certs: [{ endpoint: 'cp-catalog-opendatahub.apps.ocpq.testbbh.com',
    used_by: 'CP 360 UI route', days: 6, ticket_url: '' }],
  checks: [
    { check_id: 'H02', env_group: 'OpenShift · OCPQ',
      name: 'TLS · CP 360 route', status: 'FAIL',
      detail: 'expires in 6d', latency_ms: 61 },
    { check_id: 'H03', env_group: 'OpenShift · OCPQ',
      name: 'HTTP · CP 360 /healthz', status: 'OK', latency_ms: 182 },
    { check_id: 'H06', env_group: 'OpenShift · OCPQ',
      name: 'WebFS · CIFS write probe', status: 'WARN',
      detail: 'SLOW 1.9s', latency_ms: 1900 },
    { check_id: 'H04', env_group: 'Oracle',
      name: 'SELECT 1 · dvlpbdb1/pbdwhdbt', status: 'OK', latency_ms: 9 },
    { check_id: 'H05', env_group: 'Oracle',
      name: 'SILVER session headroom', status: 'OK',
      detail: 'value 64', latency_ms: 4 },
    { check_id: 'H08', env_group: 'Integration',
      name: 'TLS · SEI QA', status: 'WARN', detail: 'expires in 23d',
      latency_ms: 88 }] });
export const envCerts = () => ({ certs: [
  { cert_id: 'C1', endpoint: 'cp-catalog-opendatahub.apps.ocpq.testbbh.com',
    cn: '*.apps.ocpq.testbbh.com', issuer: 'BBH Internal CA',
    expires_at: '2026-08-10', days_left: 6, used_by: 'CP 360 UI route',
    group_key: 'ocpq-wildcard', owner: 'OpenShift platform' },
  { cert_id: 'C2', endpoint: 'cp-airflow.apps.ocpq.testbbh.com',
    cn: '*.apps.ocpq.testbbh.com', issuer: 'BBH Internal CA',
    expires_at: '2026-08-10', days_left: 6, used_by: 'Airflow webserver',
    group_key: 'ocpq-wildcard', owner: 'OpenShift platform' },
  { cert_id: 'C3', endpoint: 'api-qa.seic.com', cn: 'api-qa.seic.com',
    issuer: 'DigiCert TLS RSA', expires_at: '2026-08-27', days_left: 23,
    used_by: 'API Console · SEI QA env', owner: 'SEI' },
  { cert_id: 'C4', endpoint: 'jenkins.testbbh.com',
    cn: 'jenkins.testbbh.com', issuer: 'BBH Internal CA',
    expires_at: '2026-09-01', days_left: 28, used_by: 'CI pipelines',
    owner: 'Infra' },
  { cert_id: 'C5', endpoint: 'nexus.testbbh.com', cn: 'nexus.testbbh.com',
    issuer: 'BBH Internal CA', expires_at: '2026-11-14', days_left: 102,
    used_by: 'air-gap pip/npm mirror', owner: 'Infra' }] });
export const envHealth = () => ({ checks: [
  { check_id: 'H03', env_group: 'OpenShift · OCPQ',
    name: 'HTTP · CP 360 /healthz', kind: 'HTTP',
    verifies: 'route + pod + FastAPI up', status: 'OK', latency_ms: 182,
    detail: 'HTTP 200',
    strip: Array.from({ length: 30 }, () => 'OK') },
  { check_id: 'H06', env_group: 'OpenShift · OCPQ',
    name: 'WebFS · CIFS write probe', kind: 'FS',
    verifies: 'write+read a probe file', status: 'WARN',
    latency_ms: 1900, detail: 'SLOW 1.9s',
    strip: Array.from({ length: 30 },
      (_, i) => (i > 21 ? 'WARN' : 'OK')) },
  { check_id: 'H04', env_group: 'Oracle',
    name: 'SELECT 1 · dvlpbdb1/pbdwhdbt', kind: 'SQL',
    verifies: 'connect as A041327 · thick mode', status: 'OK',
    latency_ms: 9, detail: 'value 1',
    strip: Array.from({ length: 30 }, () => 'OK') }] });
export const envTopology = () => ({
  nodes: [
    { node_id: 'users', label: 'Users · analysts', icon: '👤',
      zone: 'user', sub: 'browser → F5 → route', x: 22, y: 96,
      status: 'OK' },
    { node_id: 'route', label: 'CP 360 route', icon: '🌐', zone: 'ocpq',
      sub: 'cert expires in 6 days', x: 250, y: 92, status: 'FAIL' },
    { node_id: 'fastapi', label: 'FastAPI pods', icon: '⚙', zone: 'ocpq',
      sub: 'cp-catalog-api · 2 replicas', x: 492, y: 126, status: 'OK' },
    { node_id: 'airflow', label: 'Airflow', icon: '🌀', zone: 'ocpq',
      sub: 'scheduler ♥ 12s ago', x: 250, y: 276, status: 'OK' },
    { node_id: 'oradev', label: 'dvlpbdb1 · DEV', icon: '🗄',
      zone: 'data', sub: 'pbdwhdbt · SILVER · 9ms', x: 748, y: 156,
      status: 'OK' },
    { node_id: 'webfs', label: 'WebFS · CIFS', icon: '📁', zone: 'data',
      sub: 'artifacts tree · 1.9s ▲ slow', x: 748, y: 286,
      status: 'WARN' },
    { node_id: 'apigee', label: 'Apigee egress', icon: '🛡', zone: 'dmz',
      sub: 'facade + KVM credentials', x: 1035, y: 216, status: 'OK' },
    { node_id: 'sei', label: 'SEI QA', icon: '☁', zone: 'vendor',
      sub: 'api-qa.seic.com · 310ms', x: 1262, y: 216, status: 'OK' }],
  links: [
    { link_id: 'L1', from_node: 'users', to_node: 'route',
      cert_days: 6, link_status: 'OK' },
    { link_id: 'L2', from_node: 'route', to_node: 'fastapi',
      link_status: 'OK' },
    { link_id: 'L3', from_node: 'fastapi', to_node: 'oradev',
      cert_days: 241, link_status: 'OK' },
    { link_id: 'L4', from_node: 'fastapi', to_node: 'webfs',
      link_status: 'WARN' },
    { link_id: 'L5', from_node: 'airflow', to_node: 'oradev',
      link_status: 'OK' },
    { link_id: 'L6', from_node: 'airflow', to_node: 'apigee',
      link_status: 'OK' },
    { link_id: 'L7', from_node: 'apigee', to_node: 'sei',
      cert_days: 23, link_status: 'OK' }] });
export const envPulse = () => ({
  runs: [{ run_id: 'P1', started_at: '08-05 09:00:12',
    finished_at: '08-05 09:00:52', total_n: 9, ok_n: 6, warn_n: 2,
    fail_n: 1, triggered_by: 'schedule' }],
  latest_rows: [
    { check_id: 'H01', env_group: 'OpenShift · OCPQ', kind: 'DNS',
      name: 'DNS · apps wildcard', status: 'OK', latency_ms: 4,
      detail: 'resolves', checked_at: '09:00:12' },
    { check_id: 'H02', env_group: 'OpenShift · OCPQ', kind: 'TLS',
      name: 'TLS · CP 360 route', status: 'FAIL', latency_ms: 61,
      detail: 'expires in 6d', checked_at: '09:00:12' },
    { check_id: 'H03', env_group: 'OpenShift · OCPQ', kind: 'HTTP',
      name: 'HTTP · CP 360 /healthz', status: 'OK', latency_ms: 182,
      detail: 'HTTP 200', checked_at: '09:00:13' },
    { check_id: 'H04', env_group: 'Oracle', kind: 'SQL',
      name: 'SELECT 1 · dvlpbdb1/pbdwhdbt', status: 'OK', latency_ms: 9,
      detail: 'value 1', checked_at: '09:00:15' },
    { check_id: 'H06', env_group: 'OpenShift · OCPQ', kind: 'FS',
      name: 'WebFS · CIFS write probe', status: 'WARN',
      latency_ms: 1900, detail: 'SLOW 1.9s', checked_at: '09:00:17' }] });

export const envInventory = () => ({
  inventory: [
    { inv_id: 'PBDW-SIT', platform: 'Private Banking Data Warehouse',
      ritm: 'RITM0682588', region: 'SIT',
      existing_host: 'qclpbdb1.testbbh.com / qclodiapp3q.testbbh.com',
      new_host: 'qalpbdb3.testbbh.com / qalodiapp3sei.testbbh.com / qalodidb3sei.testbbh.com',
      db_name: 'PBODIQA', sizing: 'RAM 62GB · 4TB · 8 CPU',
      status: 'In Progress', os: 'RHEL', priority: 'Critical',
      target_delivery: '2026-05-28', target_build: 'DB 6/9',
      note: 'ODI repo copied from PROD; agent installed; DB copied unmasked' },
    { inv_id: 'IMDS-DEV', platform: 'Investment Management Data Store',
      ritm: 'RITM0686013/30', region: 'DEV',
      existing_host: 'rdlimdsdb.testbbh.com (IMDSDBT)',
      new_host: 'dvlimdsdb.testbbh.com / dvlimdsapp.testbbh.com',
      db_name: 'IMDSDBLA', sizing: 'RAM 62GB · 6TB · 8 CPU',
      status: 'Completed', os: 'RHEL', priority: 'Critical',
      target_delivery: '2026-06-01', target_build: '7/20/2026',
      note: 'data copied from PROD; app servers ready' },
    { inv_id: 'PORT-TEST', platform: 'PORT (Bloomberg)', region: 'SIT',
      existing_host: 'n/a (vendor-hosted)', new_host: 'new PORT test instance',
      sizing: '25 accounts · 3000 securities', status: 'In Progress',
      os: 'Vendor', priority: 'High', target_delivery: '2026-06-30',
      note: 'separate limited test user pending (BBG)' }],
  liveness: [
    { target: 'qalpbdb3.testbbh.com', status: 'OK', detail: '10.4.22.31', checked_at: '2026-08-05 09:00' },
    { target: 'dvlimdsdb.testbbh.com', status: 'OK', detail: '10.4.31.12', checked_at: '2026-08-05 09:00' },
    { target: 'qalodidb3sei.testbbh.com', status: 'FAIL', detail: 'NXDOMAIN', checked_at: '2026-08-05 09:00' }] });
