// CP Integration Hub — independent architect review.
//
// Standpoint: data architect for a high-throughput, high-error-tolerance
// integration platform. One assumption changes: SDC events are the primary
// ingestion path. Everything from Stage 1 onward is taken exactly as the SEI
// design pack specifies it (File Ingestion Framework TDD v2.0, dbt
// Transformation TDD v2, Architecture v5).
//
// The pack was written for a file-driven pipeline. This file records what
// that one substitution breaks, what it makes expensive, and what it leaves
// with no owner. Findings are keyed to the tracker component ids in
// seiDesignTracker.js so every observation lands on something real.

export const AR_SUMMARY = {
  title: "Architect review — events-primary Integration Hub",
  line:
    "One assumption substituted: SDC events replace files as the primary ingestion path. " +
    "Stage 1 onward is unchanged from the SEI pack. 25 components are missing, 11 bottlenecks " +
    "appear that a daily file cycle never had, and 15 error paths have no owner. The inbound " +
    "event path and the outbound loader path are both unowned end to end.",
  counts: { missing: 25, bottlenecks: 11, errors: 15, mapped: 25, unchanged: 40 },
};

/* ------------------------------------------------------------------ *
 * The assumption set                                                  *
 * ------------------------------------------------------------------ */
export const AR_ASSUMPTIONS = [
  { id: "A1", holds: "changed", what: "SDC events are the primary ingestion path",
    detail: "All intraday and EOD data arrives as events. Files remain as a daily standby that is generated and held, not loaded.",
    src: "BBH decision, post-dates the pack" },
  { id: "A2", holds: "changed", what: "The envelope carries four fields and no data",
    detail: "eventid (a type code, not a message id), key, op (I/U/D), view. The event says a row changed; it never says what changed. A pull re-reads current state from the named view.",
    src: "SDC Events Structure" },
  { id: "A3", holds: "changed", what: "Micro-batch boxing on every partition of every topic",
    detail: "MB Start (1000) and MB End (1001) bracket each box, written to every partition of every domain topic. One micro-batch is one commit. Empty micro-batches are normal and complete.",
    src: "Domain Partitions — Micro Batch Boxing Pattern" },
  { id: "A4", holds: "changed", what: "At-least-once delivery, ordered within topic+partition only",
    detail: "No global ordering, no cross-topic ordering. SEI guarantees delivery and boxing; the consumer owns everything else.",
    src: "SEI producer/consumer contract" },
  { id: "A5", holds: "changed", what: "The consumer owns idempotency and cross-domain dependency",
    detail: "SEI states both explicitly as consumer responsibilities. Neither has a component in the 65.",
    src: "SEI producer/consumer contract" },
  { id: "A6", holds: "unchanged", what: "Medallion shape and the control plane",
    detail: "SWP_RAW (Bronze) → STG (a view, recomputed on read) → INT (Silver, PK = natural key + BUSINESS_DATE, 7-day retention) → DIM then FACT (Gold, DML-only MERGE, on_schema_change='fail'). DATE_CONTROL, FILE_REGISTRY, RECON_RESULT, DQ_VALIDATION_FAILURE as specified.",
    src: "dbt Transformation TDD v2 / File Ingestion TDD v2.0" },
  { id: "A7", holds: "unchanged", what: "Splunk is a write-only sink; verdicts are not stored in Oracle",
    detail: "E.6 forbids SLA_STATUS, SLA_BREACH_IND and ALERT_SENT_IND on DATE_CONTROL. PASS/WARNING is derived, never persisted.",
    src: "File Ingestion TDD v2.0 E.6, dbt TDD B.5" },
  { id: "A8", holds: "unchanged", what: "Airflow 3.0 on OpenShift, Oracle as the control store",
    detail: "Dynamic task mapping, deterministic run ids, guarded state transitions, worker pods per work item.",
    src: "File Ingestion TDD v2.0 C.1" },
];

/* ------------------------------------------------------------------ *
 * Components that do not exist in the 65                              *
 * ------------------------------------------------------------------ */
export const AR_MISSING = [
  // --- Ingress ---
  { id: "M1", plane: "Event Ingestion", name: "SDC Event Listener", pri: "P1", build: "High",
    tech: "Python · Event Hub consumer",
    deliverable: "Consumer group per domain topic; durable write then offset commit",
    perf: "Throughput ceiling is partition count × one consumer per partition. Partition count is unstated, so the ceiling is unknown and unprovable.",
    err: "Offset must be committed only after the durable write. The reverse order loses events silently on a crash — the single most damaging ordering mistake available here.",
    why: "There is no component between SEI publishing and Stage 1 holding rows. Components 8 and 9 are file sensors." },
  { id: "M2", plane: "Ingress/Egress", name: "Callback Receiver", pri: "P1", build: "Medium",
    tech: "Python · Apigee-fronted endpoint",
    deliverable: "Authenticate, validate envelope shape, durable write, 202",
    perf: "Must not do correlation work inline. Parsing and matching belong downstream of the acknowledgement.",
    err: "Acknowledge on durable write, never on successful processing. A 500 because a lookup failed ties SEI's retry behaviour to BBH's internal bugs.",
    why: "SEI pushes loader status. Component 10 covers producing outbound payloads, nothing receives." },
  { id: "M3", plane: "Ingress/Egress", name: "Loader Submission Registry", pri: "P1", build: "High",
    tech: "Oracle DDL + Python",
    deliverable: "LOADER_SUBMISSION · LOADER_STATUS_HISTORY (with SOURCE) · LOADER_ERROR",
    perf: "Error detail is fetched once on reaching terminal-with-errors, paginated and stored. Re-fetching per poll pulls the same rejected records repeatedly.",
    err: "Without a row written at send time, a submission that never reached SEI is indistinguishable from one that succeeded. Silence looks exactly like success.",
    why: "The outbound path has no FILE_REGISTRY equivalent anywhere in the pack or the 65." },

  // --- Processing ---
  { id: "M4", plane: "Event Ingestion", name: "Key-Set Collapser", pri: "P1", build: "High",
    tech: "Python",
    deliverable: "Per micro-batch, per view: one distinct key set with op precedence",
    perf: "This component decides the entire cost model. Collapsing 50,000 events to 8,000 distinct keys is the difference between one query and fifty thousand.",
    err: "D must win over I and U for the same key inside one micro-batch, or a deleted row is re-pulled and resurrected. Unknown view or unknown op needs a disposition, not a crash.",
    why: "Nothing in the pack collapses anything; the file path has no equivalent problem." },
  { id: "M5", plane: "Event Ingestion", name: "Set-Based Puller", pri: "P1", build: "High",
    tech: "Python · SEI view API",
    deliverable: "One bound, set-based retrieval per view per micro-batch",
    perf: "The system's throughput ceiling. Oracle's 1000-element IN limit forces a global temporary table or array bind with a join — an IN list built by string concatenation will fail in production and silently truncate in test.",
    err: "Needs a circuit breaker. If SEI's view API degrades, retrying every micro-batch amplifies load against an already failing dependency.",
    why: "Per-event retrieval is the default anyone reaches for and it is ruinous — see bottleneck B1." },
  { id: "M6", plane: "Event Ingestion", name: "Intraday Stage-1 Loader", pri: "P1", build: "Medium",
    tech: "Python · Oracle array insert",
    deliverable: "Continuous micro-batch load into Stage 1 with one commit per micro-batch",
    perf: "Array insert with a tuned batch size, one commit per micro-batch. Row-by-row insert and per-row commit is the classic first wall and it arrives early.",
    err: "A failed micro-batch rolls back whole. A partially loaded micro-batch marked LOADED is the defect that makes the EOD gate lie.",
    why: "Component 13 is a file ingestion framework. The event path loads continuously, not once a day." },

  // --- Orchestration ---
  { id: "M7", plane: "Event Ingestion", name: "Domain Sequencer", pri: "P1", build: "Medium",
    tech: "Python · Airflow",
    deliverable: "Static ordering End Client → Account → Transaction, derived from the view field",
    perf: "Serialises what could run in parallel. Only serialise when a micro-batch actually contains both domains; otherwise the ordering cost is paid 288 times a day for nothing.",
    err: "A dimension event in a later micro-batch than its fact falls to hold-and-replay, and the 7-day cliff starts ticking from that moment.",
    why: "SEI assigns cross-domain dependency to the consumer. No component owns it." },
  { id: "M8", plane: "Orchestration", name: "Event Gate Evaluator", pri: "P1", build: "Medium",
    tech: "Python · Oracle",
    deliverable: "Replaces E.2's MINUS: every micro-batch LOADED, plus the EOD marker received",
    perf: "Trivial to compute. Its cost is entirely in being wrong.",
    err: "Gating on the marker alone lets the transformation run on short Stage 1 — and STG→INT still reconciles, because it ties against a Stage 1 that is itself short.",
    why: "E.2 counts DAILY interfaces MINUS ARCHIVED. Under events there is no interface to count and nothing reaches ARCHIVED." },
  { id: "M9", plane: "Orchestration", name: "SEI Status Poller", pri: "P2", build: "Medium",
    tech: "Python · Airflow · Apigee",
    deliverable: "Non-terminal submissions only, tiered cadence, detail fetch on terminal",
    perf: "Terminal submissions must drop out of the poll set, or Apigee call volume grows with history rather than with work in flight.",
    err: "A submission past max age becomes STATUS_UNRESOLVED rather than sitting at SUBMITTED for ever. When push and poll disagree, the poll wins and terminal never regresses.",
    why: "The backstop for a notification that never arrives. Nothing in the 65 calls SEI for status." },

  // --- Data Quality ---
  { id: "M10", plane: "Event Ingestion", name: "Sequence Gap Detector", pri: "P1", build: "Medium",
    tech: "Python · SQL",
    deliverable: "Monotonic sequence numbers per partition; a gap is a provably lost event",
    perf: "One ordered scan per partition per micro-batch. Cheap.",
    err: "This is the strongest completeness proof in the whole estate and it currently has no owner. The file channel has nothing comparable.",
    why: "Absent from the pack and from the 65, despite costing almost nothing." },
  { id: "M11", plane: "Event Ingestion", name: "G0 Envelope Gate", pri: "P1", build: "Medium",
    tech: "Python",
    deliverable: "Per-envelope structural validation before staging",
    perf: "Must run in the consumer loop, so it has to be O(1) per envelope with no database lookup.",
    err: "Unknown eventid, unresolvable view, invalid op, missing key. Each needs a disposition. Without a dead-letter path a single poison envelope stalls its partition for ever.",
    why: "G1 validates a file's structure. Nothing validates an envelope." },

  // --- Foundation ---
  { id: "M12", plane: "Event Ingestion", name: "Event Staging Store", pri: "P1", build: "High",
    tech: "Oracle DDL",
    deliverable: "(topic, partition, offset, sequence_number, enqueued_ts, eventid, key, op, view)",
    perf: "The unique index on (topic, partition, offset) sits on the hot insert path. Range-partition by business date with local indexes, or the index becomes the bottleneck rather than the guard.",
    err: "This is layer one of idempotency: a consumer replay yields the same offset and is rejected by the constraint.",
    why: "Entirely BBH-owned and nobody is writing it. Ship it without enqueued_ts and sequence_number and lag and gap detection are not computable at all." },
  { id: "M13", plane: "Event Ingestion", name: "Micro-Batch Registry", pri: "P1", build: "High",
    tech: "Oracle DDL + Python",
    deliverable: "(topic, partition, mb_id) with state, counts and both box timestamps",
    perf: "Small table, high update rate. One row per partition per micro-batch per topic — at a five-minute cadence that is still tens of thousands of rows a day.",
    err: "A start with no end, or a partition that never reported, is the only way to see a stalled producer. Without the partition count as a denominator, 'all partitions reported' is unprovable.",
    why: "The event channel's FILE_REGISTRY. It does not exist." },
  { id: "M14", plane: "Event Ingestion", name: "Idempotency Service", pri: "P1", build: "High",
    tech: "Python · Oracle",
    deliverable: "Two layers: offset uniqueness, then key-set collapse per view per micro-batch",
    perf: "Layer one is an index write. Layer two is free — it falls out of M4.",
    err: "A producer retry arrives at a different offset with identical content, so layer one cannot see it. Only collapsing to a distinct key set neutralises it.",
    why: "SEI assigns idempotency to the consumer in writing. No component accepts it." },
  { id: "M15", plane: "Event Ingestion", name: "Event Quarantine", pri: "P1", build: "High",
    tech: "Oracle DDL + Python",
    deliverable: "Dead-letter with a reason taxonomy and a bounded replay counter",
    perf: "n/a",
    err: "A file that fails becomes QUARANTINED. An event that fails has nowhere to go. Reasons needed: unknown view, invalid op, key not found, pull timeout, unparseable envelope, sequencer cycle.",
    why: "Component 29 is a file quarantine. The event path has no equivalent and therefore no poison-pill escape." },
  { id: "M16", plane: "Event Ingestion", name: "Consumer Lag Monitor", pri: "P1", build: "Low",
    tech: "Python · Splunk",
    deliverable: "Per-partition lag from broker enqueue metadata",
    perf: "n/a",
    err: "Lag is the only intraday health signal there is. The envelope carries no timestamp of its own, so lag must come from broker metadata captured at receipt — which is why M12 needs enqueued_ts.",
    why: "Component 34 Observability predates events and has no lag concept." },
  { id: "M19", plane: "Foundation", name: "Loader Template Registry", pri: "P1", build: "High",
    tech: "Oracle DDL + Python",
    deliverable: "The 24 SEI loader templates, versioned, with attribute obligation and validation rules",
    perf: "Cached per run. One read per loader type, never per record.",
    err: "The template version in force at generation must be pinned onto the submission. An error SEI returns against last week’s submission can only be read against the version in force that day — and the catalogue already shows v1.24, v1.21 and v9 live together.",
    why: "Data 360 holds the loader definitions with every attribute typed Mandatory, Conditional or Optional plus its validations. Nothing in the Hub reads them, so those obligations exist only as documentation." },
  { id: "M20", plane: "Data Quality", name: "G6 Outbound Validation Gate", pri: "P1", build: "High",
    tech: "Python · SQL",
    deliverable: "Pre-submission validation against the template: obligation, type, domain, referential, control totals",
    perf: "Set-based over the generated extract, never a lookup per record. Validating 40,000 rows one at a time against Gold is the outbound twin of per-event retrieval.",
    err: "This gate decides whether a defect is caught by BBH in seconds or by SEI in hours. Its verdict must block submission rather than warn — an advisory outbound gate is the same as no gate.",
    why: "G1 to G5 all face inbound. Nothing validates anything on the way out, so today the first validator of a BBH loader is SEI." },
  { id: "M21", plane: "Ingress/Egress", name: "Loader Payload Store", pri: "P1", build: "Medium",
    tech: "Oracle DDL + object store",
    deliverable: "What was generated and what was sent, with a content hash, written before submission",
    perf: "Store the artefact once and reference it. Never regenerate it to answer a question about it.",
    err: "Write before send, in that order. A payload recorded only after a successful send cannot explain a send that failed halfway, and a rejection arriving two days later has nothing to be read against.",
    why: "Without it a rejected record cannot be tied to the bytes that caused it, and a disagreement with SEI has no evidence on the BBH side." },
  { id: "M22", plane: "Foundation", name: "Outbound Quarantine & Correction", pri: "P1", build: "High",
    tech: "Python · Oracle",
    deliverable: "Rejected records held, with the correction protocol and resubmission lineage",
    perf: "n/a",
    err: "A retry and a correction are different operations. A retry reuses the submission identifier because the same payload goes again; a correction is a new submission carrying corrects_submission_id, because the payload changed. Collapsing the two makes sent-versus-accepted unprovable.",
    why: "Component 29 quarantines inbound files. Rejected outbound records have nowhere to go and no defined route back." },
  { id: "M23", plane: "Data Quality", name: "Outbound Reconciliation", pri: "P1", build: "Medium",
    tech: "Python · SQL",
    deliverable: "Generated → validated → submitted → accepted → rejected: five counts that must tie",
    perf: "Daily set-based aggregate per loader type.",
    err: "RECON_RESULT’s three boundaries are all inbound. Sent versus accepted is a boundary that exists nowhere, so a loader that silently dropped three percent of its records on the way out is invisible to every control in the estate.",
    why: "The outbound counterpart of the four event-side boundaries. Same omission, opposite direction." },
  { id: "M24", plane: "Processing", name: "Transformation Rule Registry", pri: "P1", build: "High",
    tech: "Oracle DDL + BA authoring surface",
    deliverable: "Stage 2 to Gold mapping and business logic as versioned, effective-dated data rather than SQL",
    perf: "Read once per dbt run and cached. Nothing in the registry is evaluated row by row \u2014 it is compiled ahead of the run, not interpreted during it.",
    err: "Effective dating is not optional. A rule that changed on 1 March must still explain a row loaded on 28 February, so every Gold row carries the RULE_SET_VERSION that produced it. Without that, restatement is unreproducible \u2014 the same defect the event pull already has.",
    why: "Today a mapping change is a code change: a PR, a review, a release. The people who own the business meaning of a column cannot change it, and the people who can do not own the meaning." },
  { id: "M25", plane: "Processing", name: "Rule-to-dbt Compiler", pri: "P1", build: "High",
    tech: "Python \u00b7 dbt \u00b7 CI",
    deliverable: "Generates dbt models from the rule registry; the generated SQL is reviewed in a pull request like any other",
    perf: "Compile time, not run time. A runtime rule interpreter inside the warehouse would be slower, unobservable and would lose dbt\u2019s lineage, tests and documentation.",
    err: "Every rule needs at least one expectation \u2014 sample input, expected output \u2014 running in CI. Without it a BA ships broken SQL confidently, and the first thing anyone notices is a wrong number in Gold.",
    why: "The alternative, interpreting rules at run time, is how externalisation usually fails. Generating dbt keeps every existing guarantee and makes the BA\u2019s change visible as a SQL diff." },
  { id: "M17", plane: "Foundation", name: "Schema Contract Registry", pri: "P1", build: "Medium",
    tech: "Oracle DDL + CI",
    deliverable: "Per-view column contract, versioned, checked before the pull is trusted",
    perf: "One cached read per view per run.",
    err: "FILE_SCHEMA_CONFIG holds no column mapping, so RAW DDL is the schema contract, while Gold runs on_schema_change='fail'. A column added upstream breaks the pipeline by design with no notification path. This component is the guard.",
    why: "The most predictable future incident in the pack, and nothing watches for it." },
  { id: "M18", plane: "Foundation", name: "Expectation Store", pri: "P1", build: "Medium",
    tech: "Oracle DDL",
    deliverable: "Interface calendar, loader cadence, marker schedule, event cadence baseline",
    perf: "n/a",
    err: "Without it nothing can be late, only absent. On the event channel lateness is derivable from the stream's own rhythm; on every other channel it needs a stated expectation.",
    why: "EXPECTED_INTERFACE_CALENDAR and REQUIRED_IND are still proposals, and no channel has an expectation model." },
];

/* ------------------------------------------------------------------ *
 * Performance bottlenecks                                             *
 * ------------------------------------------------------------------ */
export const AR_BOTTLENECKS = [
  { id: "B1", sev: "critical", title: "The pull is the system's throughput ceiling",
    comp: ["M5", "M4"],
    body: "Query count is driven by cadence × views, not by account count. A five-minute cadence is 288 cycles a day; the reference client ran 17,955 queries a month, about 2.08 per cycle. Ten views at the same cadence is roughly 86,000 queries a month. Scaling the estimate by accounts understates it badly, because accounts do not appear in the formula.",
    fix: "One set-based query per view per micro-batch, bound to a collapsed key set. Never one query per event. Oracle's 1000-element IN limit means a global temporary table or an array bind with a join — a concatenated IN list fails in production and truncates silently in test." },

  { id: "B2", sev: "critical", title: "STG is a view, and events make it run 288 times a day",
    comp: ["15", "M6"],
    body: "The dbt TDD defines STG as a view, recomputed on read. Under a daily file cycle it is recomputed once. Under intraday events, INT is built incrementally all day, so the STG view is recomputed on every incremental run — and each recomputation scans Stage 1. This is the single largest cost the event substitution introduces, and it comes from a design decision that was entirely reasonable when it was made.",
    fix: "Either materialise STG per micro-batch, or ensure the INT incremental predicate pushes down to Stage 1's partition so the view scans one micro-batch rather than the whole accumulated day. Verify the push-down on the actual plan; do not assume it." },

  { id: "B3", sev: "high", title: "Airflow task volume multiplies by roughly 300×",
    comp: ["18", "51"],
    body: "The scheduler polls its metadata database continuously and uses SELECT FOR UPDATE in its loop. Moving from about one DAG run a day to 288 intraday runs, each with per-domain dynamic task mapping, multiplies task_instance rows by two to three orders of magnitude. Nothing in the pack has costed the scheduler itself.",
    fix: "Size the scheduler and its database for the new task rate before build, set an aggressive metadata retention policy, and consider one long-running consumer rather than 288 scheduled DAG runs." },

  { id: "B4", sev: "high", title: "Event staging insert rate",
    comp: ["M12", "M6"],
    body: "A Python consumer writing envelope rows one at a time is the first wall every event pipeline hits. The unique index on (topic, partition, offset) sits directly on the hot insert path, so the guard that gives idempotency is also the thing that slows the write.",
    fix: "Array insert with a tuned batch size and one commit per micro-batch. Range-partition the staging table by business date with local indexes so index maintenance stays inside the current partition." },

  { id: "B5", sev: "high", title: "DQ gates were designed per file, not per micro-batch",
    comp: ["23", "24", "26", "27"],
    body: "G2 profiling, G4 tie-out and G5 post-publish recon are set-level aggregates. Running them per micro-batch means 288 full aggregate passes a day. Running them only daily means an intraday defect is invisible until the gate.",
    fix: "Split by cost class: G0 and G1 and G3 per micro-batch because they are row-level and cheap; G2, G4 and G5 at the EOD gate because they are set-level and expensive. State the split rather than leaving it to whoever writes the DAG." },

  { id: "B6", sev: "high", title: "INT's incremental MERGE into a growing current-day partition",
    comp: ["15", "M6"],
    body: "INT is partitioned by BUSINESS_DATE with a 7-day window. Under intraday events the current day's partition is written to continuously, and an incremental MERGE against a partition that grows all day degrades as the day goes on. The 6pm micro-batch is materially slower than the 6am one.",
    fix: "Subpartition by micro-batch, or load append-only with a late dedupe at the gate. Measure the degradation curve before choosing; it may be acceptable at real volumes, but nobody knows the real volumes." },

  { id: "B7", sev: "medium", title: "Oracle session concurrency under intraday fan-out",
    comp: ["55", "18"],
    body: "Connection pooling was sized for a daily per-domain fan-out. Intraday micro-batches multiply concurrent sessions by the cadence, and Airflow dynamic task mapping spawns a worker pod per work item, each opening its own connections.",
    fix: "Bound the pool per pod and the pod count per micro-batch. An unbounded fan-out against a shared Oracle is how one pipeline takes down another team's service." },

  { id: "B8", sev: "medium", title: "DIM-before-FACT serialisation is now paid per micro-batch",
    comp: ["19", "M7"],
    body: "Under a daily batch the ordering cost is paid once. Under intraday it is paid 288 times, including on the many micro-batches that contain only one domain and need no ordering at all.",
    fix: "Serialise only when the micro-batch actually contains both domains. Inspect the collapsed key set before choosing the execution shape." },

  { id: "B9", sev: "medium", title: "Splunk ingest volume",
    comp: ["34", "M16"],
    body: "Thirteen operational signals, multiplied by 288 cycles and by domain, is a different order of magnitude from a daily file pipeline. Splunk ingest is metered and rate limited.",
    fix: "Emit per micro-batch only what is actionable; aggregate the rest to a per-cycle or per-hour rollup. Decide this before the contract is written, not after the first bill." },

  { id: "B11", sev: "high", title: "Outbound validation done per record instead of per extract",
    comp: ["M20", "10"],
    body: "G6 has to check obligation, type, domain and referential integrity across every row of a generated extract. Written as a per-record lookup against Gold it is the outbound twin of per-event retrieval, and it lands on the same Oracle the pipeline is already loading.",
    fix: "Set-based validation over the staged extract, one pass per rule, with control totals computed in the same pass. Validate the artefact, not the rows." },

  { id: "B10", sev: "medium", title: "Pull latency is inside the micro-batch's critical path",
    comp: ["M5", "M6"],
    body: "The box is not complete until every view has been pulled and loaded. A single slow view holds the whole micro-batch, and the next micro-batch is already arriving. Queueing under a fixed cadence is how a small latency regression becomes an unbounded backlog.",
    fix: "Bound the pull with a timeout and an explicit partial disposition, and monitor the ratio of micro-batch duration to cadence interval. Above roughly 0.7 the system has no recovery headroom left." },
];

/* ------------------------------------------------------------------ *
 * Error paths with no owner                                           *
 * ------------------------------------------------------------------ */
export const AR_ERRORS = [
  { id: "E1", sev: "critical", title: "Offset committed before the durable write",
    comp: ["M1", "M12"],
    body: "If the consumer commits its offset and then crashes before the staging write lands, those events are gone and nothing records that they existed. The loss is silent and permanent — there is no gap to detect, because the sequence numbers were never stored.",
    owner: "Nothing in the pack states the ordering. Write, then commit." },
  { id: "E2", sev: "critical", title: "Poison envelope stalls a partition indefinitely",
    comp: ["M11", "M15"],
    body: "Ordering is guaranteed within a partition, so a single unprocessable envelope blocks everything behind it until a human intervenes. At-least-once redelivery means it returns for ever.",
    owner: "No dead-letter path exists for events. Component 29 quarantines files." },
  { id: "E3", sev: "critical", title: "Replay does not reproduce the original load",
    comp: ["21", "M5"],
    body: "The file path replays identical bytes and gets an identical result. The event pull re-reads current state, so replaying yesterday's micro-batch today returns today's values. The recovery procedures in D.1 to D.6 are written entirely in file terms and do not survive the substitution.",
    owner: "Either store the pulled payload, or obtain as-of retrieval from SEI. Neither is specified." },
  { id: "E4", sev: "critical", title: "The gate cannot detect event loss",
    comp: ["M8", "30"],
    body: "A micro-batch that fails at 11am and goes unnoticed means the EOD transformation runs on short Stage 1 — and STG→INT reconciles cleanly, because it ties against a Stage 1 that is itself short. The existing three boundaries are all downstream of the loss and cannot see it.",
    owner: "Requires the four event-side boundaries and a gate that demands every micro-batch LOADED." },
  { id: "E5", sev: "high", title: "Not-found key on pull has no disposition",
    comp: ["M5", "28"],
    body: "The key changed and by the time the pull runs the row is gone — a delete race, and at low rates entirely normal. At high rates it is a symptom of something serious. Treating it as an error alarms constantly; treating it as normal hides real loss.",
    owner: "Needs a rate threshold tied to the observed delete rate, not a binary rule." },
  { id: "E6", sev: "high", title: "Partial micro-batch failure across views",
    comp: ["22", "M6"],
    body: "If three of five views pull successfully and the fourth times out, is the micro-batch FAILED and rolled back whole, or PARTIAL and advanced? Component 22 sets a partial-batch policy for files and says nothing about views inside a box.",
    owner: "Unowned. The safe default is roll back whole; the useful default is not, and somebody has to choose." },
  { id: "E7", sev: "high", title: "Consumer rebalance in the middle of a box",
    comp: ["M1", "M13"],
    body: "A group rebalance mid-micro-batch moves a partition to a different consumer, so MB Start and MB End for that partition land on different processes with different in-memory state.",
    owner: "Nothing coordinates a box across a rebalance. The registry has to be the coordination point, not process memory." },
  { id: "E8", sev: "high", title: "No circuit breaker on the SEI view API",
    comp: ["M5"],
    body: "If SEI's retrieval degrades, every micro-batch retries against an already failing dependency and amplifies the load. The classic retry storm, with a fixed cadence guaranteeing it repeats.",
    owner: "Needs a breaker with backoff and an explicit degraded mode that stops pulling and keeps staging." },
  { id: "E9", sev: "high", title: "op = D semantics are undefined downstream",
    comp: ["17", "M4"],
    body: "A delete event names a key whose row no longer exists to pull. Correction Handling is written for restatement and in-place merge, not for a delete arriving as an event. Whether a delete soft-closes the INT row, removes it, or writes a tombstone is unstated.",
    owner: "Component 17 predates events entirely." },
  { id: "E10", sev: "medium", title: "Replay has no attempt limit",
    comp: ["21", "M15"],
    body: "The Replay / Rerun Engine has no maximum attempt count before a work item is quarantined. A permanently failing item retries for ever and consumes capacity every cycle.",
    owner: "Bounded retry plus quarantine. Trivial to add now, painful to retrofit." },
  { id: "E11", sev: "medium", title: "Outbound has no error model at all",
    comp: ["10", "M3"],
    body: "Loader submissions have no registry, no status history, no error store and no correction protocol. A retry reuses the submission id; a correction is a new submission that references the one it corrects. Neither is defined.",
    owner: "The whole outbound half of the estate." },
  { id: "E13", sev: "critical", title: "Nothing validates a loader before it is published",
    comp: ["M20", "10"],
    body: "There is no outbound gate. A loader violating an obligation the template declares — a missing Mandatory attribute, a Conditional one whose trigger fired, a code outside its domain — goes to SEI and returns as a rejection hours later, by which time the business date has moved on. G1 to G5 all face inbound.",
    owner: "Unowned. Today the first validator of a BBH loader is SEI." },
  { id: "E14", sev: "high", title: "No record of what was actually sent",
    comp: ["M21", "M3"],
    body: "A rejection names records in a payload nobody kept. Without the generated artefact and its hash written before submission, a reject cannot be tied back to the bytes that caused it, a partial send cannot be told from a complete one, and a disagreement with SEI has no evidence on the BBH side.",
    owner: "Unowned. The submission registry records that a send happened, not what it contained." },
  { id: "E15", sev: "high", title: "A Gold row cannot be explained by the rule that produced it",
    comp: ["M24", "16"],
    body: "Transformation logic lives in dbt SQL at a commit. Three months later, explaining why a figure came out as it did means finding the commit that was deployed that night and reading it \u2014 assuming the model was not changed for an unrelated reason in between. Nothing on the row records which version of the logic produced it.",
    owner: "Unowned. Externalising the rules without effective dating and a RULE_SET_VERSION stamp would make this worse, not better: more people changing logic, still no record of which logic ran." },
  { id: "E12", sev: "medium", title: "Dimension arriving after fact starts the 7-day clock",
    comp: ["M7", "17"],
    body: "Hold-and-replay handles a fact whose dimension has not arrived, marking MISSING_DIMENSION_KEY with reprocess_eligible. But INT retains seven days, so a dimension that arrives on day eight means the held fact is silently gone from FACT for ever.",
    owner: "The cliff is real and nothing surfaces days-to-expiry on held rows." },
];

/* ------------------------------------------------------------------ *
 * Findings mapped onto the existing 65                                *
 * ------------------------------------------------------------------ */
export const AR_FINDINGS = [
  { id: "8", verdict: "demoted", name: "Landing Zone + Transport",
    finding: "Becomes the standby path. It also conflicts with the SEI pack: this design uses a manifest written last plus deferrable sensors verifying size and mtime, while the File Ingestion TDD discovers by filename pattern every five minutes with no manifest at all. Two different transport contracts with the same upstream party.",
    action: "Pick one contract. The manifest protocol is stronger; the TDD is what is being built." },
  { id: "9", verdict: "demoted", name: "File Arrival Sensors",
    finding: "Deferrable sensors idling all day for a path that now only needs to prove a file was generated and held. The registry gains no state meaning 'available and deliberately unused', so a standby file looks either permanently missing or falsely satisfies a gate that should not be running.",
    action: "Add the state. Reduce the sensor to a readiness check." },
  { id: "10", verdict: "gap", name: "Outbound Producers",
    finding: "One component carrying a whole framework. It covers generating and sending, and nothing else exists: no template registry, no validation before publish, no record of what was sent, no quarantine for rejects, no sent-versus-accepted reconciliation, no receiver, no poller, no submission registry. The inbound path has a gate, a quarantine and reconciliation boundaries; the outbound path has none of the three.",
    action: "Eight components hang off this one: M19 and M20 before the send, M21 at the moment of the send, M3, M2 and M9 around the return leg, M22 and M23 to close the loop." },
  { id: "13", verdict: "rebuild", name: "Python Ingestion Framework",
    finding: "Written as a file ingestion framework: discover work items, process a file, evaluate completeness. The event path shares none of that shape — it consumes continuously, collapses, pulls and loads per micro-batch.",
    action: "Do not extend this component with an event mode. Build M1, M4, M5 and M6 alongside it and let this one own the standby path." },
  { id: "14", verdict: "amend", name: "Stage 1 RAW",
    finding: "Needs a micro-batch identifier column to make a load traceable to its box, and a commit boundary of one micro-batch. Without the column, lineage from a Gold row stops at the business date.",
    action: "Add MICROBATCH_ID. Free now, a change request later." },
  { id: "15", verdict: "bottleneck", name: "Stage 2 Enriched (dbt)",
    finding: "Two problems. This design names a Pre-Gold Exadata tier and an Enriched layer that the SEI pack does not have; the pack has STG as a view and INT as Silver. And the STG view is recomputed on every incremental run, which events turn from once a day into 288 times a day.",
    action: "Reconcile the layer model first, then B2." },
  { id: "16", verdict: "risk", name: "Gold (dbt)",
    finding: "Two risks. on_schema_change='fail' with DML-only MERGE is correct for safety, and it means an upstream column addition halts the pipeline with no notification path and no forward fix that is not a deploy. Separately, every Stage 2 to Gold mapping and derivation is hand-written SQL, so a business rule change is an engineering release and the people who own the meaning of a column cannot change it.",
    action: "M17 plus a schema-change protocol with SEI for the first. M24 and M25 for the second \u2014 externalise the rules as versioned data and generate the dbt models from them." },
  { id: "17", verdict: "gap", name: "Correction Handling",
    finding: "Written for restatement and in-place merge. A delete arriving as an event has no defined downstream behaviour, and an outbound correction — a new submission referencing the one it corrects — is not modelled at all.",
    action: "Define op=D semantics and the outbound correction protocol." },
  { id: "18", verdict: "bottleneck", name: "Airflow DAG + Per-Domain Fan-out",
    finding: "Task volume multiplies by roughly 300× under intraday micro-batches with dynamic task mapping.",
    action: "B3. Consider a long-running consumer instead of 288 scheduled runs." },
  { id: "19", verdict: "bottleneck", name: "Dim-before-Fact / dbt Threads",
    finding: "The ordering cost moves from once a day to once per micro-batch, including on boxes containing a single domain.",
    action: "B8 — order conditionally on the collapsed key set." },
  { id: "20", verdict: "rebuild", name: "Intraday Cadence Control",
    finding: "The one component that anticipated intraday, but defined as a batch lane running more often. Event cadence is not a schedule — it is the stream's own rhythm, and lateness comes from a rolling baseline of the inter-micro-batch interval.",
    action: "Redefine around micro-batch cadence and consumer lag." },
  { id: "21", verdict: "broken", name: "Replay / Rerun Engine",
    finding: "Its core assumption does not survive events. Replaying a micro-batch re-reads current state and returns today's values, not the values as of the original event. It also has no maximum attempt count.",
    action: "E3 and E10. This is the component most damaged by the substitution." },
  { id: "22", verdict: "gap", name: "Partial-Batch Policy",
    finding: "Sets policy for partial file batches. Silent on partial view failure inside a micro-batch, which is the equivalent case and the more frequent one.",
    action: "E6." },
  { id: "23", verdict: "amend", name: "G1 File / Structural Gate",
    finding: "Validates a file's structure. Nothing validates an envelope, so an unknown view or invalid op reaches the collapser.",
    action: "M11, and keep G1 for the standby path." },
  { id: "24", verdict: "bottleneck", name: "G2 RAW Profiling Gate",
    finding: "A set-level aggregate. Per micro-batch it runs 288 times a day.",
    action: "B5 — move to the EOD gate." },
  { id: "26", verdict: "bottleneck", name: "G4 Tie-out / Control Totals",
    finding: "Full-table control totals. Same cost class as G2 and the same 288× exposure.",
    action: "B5 — EOD gate only, and it is the gate's strongest check." },
  { id: "27", verdict: "ok", name: "G5 Post-Publish Recon",
    finding: "Already daily and post-publish. Unaffected by the substitution, provided it is not naively moved to per micro-batch for symmetry.",
    action: "Leave alone." },
  { id: "28", verdict: "gap", name: "DQ Framework",
    finding: "No event DQ taxonomy. The failure modes of an envelope and a pull — unknown view, key not found, pull timeout, sequencer cycle — have no codes and therefore no reporting.",
    action: "Extend the taxonomy before the codes are invented ad hoc in three places." },
  { id: "29", verdict: "gap", name: "Error Handling & Quarantine",
    finding: "A file quarantine. The event path has no dead-letter, so a poison envelope has no escape and stalls its partition.",
    action: "M15 — the highest-value single addition in this review." },
  { id: "30", verdict: "gap", name: "Reconciliation Framework",
    finding: "Three boundaries, all downstream of Stage 1 and all inbound. The event path adds four upstream of them — events received → distinct keys → rows pulled → Stage 1 loaded — and the outbound path adds five that exist nowhere: generated → validated → submitted → accepted → rejected. Loss in either direction is currently undetectable by construction.",
    action: "Add the four inbound (E4) and the five outbound (M23)." },
  { id: "31", verdict: "degraded", name: "Audit & Lineage",
    finding: "Because the pull re-reads current state, lineage runs Gold row → micro-batch → key and never Gold row → the specific change that caused it. That is a permanent reduction in what lineage can answer, and it should be stated rather than discovered.",
    action: "State the limit. Add MICROBATCH_ID to carry what remains." },
  { id: "33", verdict: "amend", name: "Metadata & Configuration Store",
    finding: "Needs three new catalogues: the view catalogue, the eventid → domain/view map, and the expectation store.",
    action: "M17 and M18 land here." },
  { id: "34", verdict: "gap", name: "Observability",
    finding: "No consumer lag, no sequence gap detection, no micro-batch state. The primary ingestion path is unobserved, and Splunk volume is about to change order of magnitude.",
    action: "M16, M10, B9." },
  { id: "55", verdict: "bottleneck", name: "Oracle Connection Pooling",
    finding: "Sized for daily fan-out. Intraday multiplies concurrent sessions by the cadence, with a worker pod per mapped task opening its own connections.",
    action: "B7 — bound the pool per pod and the pods per micro-batch." },
  { id: "62", verdict: "gap", name: "HA / DR",
    finding: "No RPO or RTO anywhere in the pack. Under events, Event Hub retention *is* the recovery window and therefore the RTO — and retention is unstated.",
    action: "State retention, then derive RPO and RTO from it rather than the reverse." },
];

export const AR_VERDICTS = {
  broken:     ["#b3261e", "assumption does not survive"],
  bottleneck: ["#a8560f", "works, but not at this rate"],
  rebuild:    ["#6d3ac0", "wrong shape for events"],
  gap:        ["#cc3344", "nothing owns this"],
  risk:       ["#a8560f", "correct and dangerous"],
  degraded:   ["#8a6d1f", "capability permanently reduced"],
  amend:      ["#0b5e83", "small change, free now"],
  demoted:    ["#5c7c94", "still needed, no longer primary"],
  ok:         ["#159943", "unaffected"],
};

export const AR_SEV = {
  critical: "#b3261e",
  high:     "#d97706",
  medium:   "#0b5e83",
};

/* ------------------------------------------------------------------ *
 * Provenance — is the gap the SEI pack's, the BBH 65's, or both?      *
 * `owner` says who should answer for it, so the right list goes to    *
 * the right meeting. Asking SEI about a BBH-owned component wastes    *
 * the conversation.                                                   *
 * ------------------------------------------------------------------ */
export const AR_SEI_COVER = {
  covered: ["#159943", "specified in the SEI pack"],
  partial: ["#a8560f", "partly specified — named, not sufficient"],
  absent:  ["#cc3344", "nothing in the SEI pack"],
};
export const AR_OWNER = {
  SEI:   ["#6d3ac0", "SEI must answer"],
  Joint: ["#0b5e83", "needs both sides"],
  BBH:   ["#5c7c94", "BBH-owned — do not ask SEI"],
};

// keyed by tracker id (originals) or AR id (the 23 additions)
export const AR_COVERAGE = [
  /* ---- Ingress / Egress ---- */
  { id: "8", sei: "covered", owner: "Joint",
    ask: "The pack discovers by filename pattern every five minutes with no manifest. This design uses a manifest written last plus size and mtime verification. Which transport contract is the real one?",
    rec: "Settle on one before build. The manifest is the stronger guarantee; the TDD is what is being built. Whichever wins, the other document has to change." },
  { id: "9", sei: "covered", owner: "Joint",
    ask: "Under events the files are standby. Is there a registry state meaning 'available and deliberately unused'?",
    rec: "Add the state. Without it a standby file looks either permanently missing or falsely satisfies a gate that should not be running." },
  { id: "10", sei: "absent", owner: "SEI",
    ask: "The pack is entirely inbound. There is no outbound section at all. What is the loader submission, acknowledgement and error contract?",
    rec: "Treat outbound as a first-class half of the design rather than an appendix. Eight components hang off this one." },
  { id: "11", sei: "partial", owner: "Joint",
    ask: "Is Apigee a firm decision or a placeholder (AD-3), and does it front both the submit path and the status-return path?",
    rec: "Settle AD-3 before the callback receiver is built; it decides auth, rate limits and who owns the error envelope." },
  { id: "M2", sei: "absent", owner: "SEI",
    ask: "Will SEI supply a message_id on the status push that survives its own retry, and what is the retry behaviour on a 5xx from the BBH endpoint?",
    rec: "Acknowledge on durable write. The inbox belongs to the Hub with Integration360 as a second consumer, so an observability tool is never on the remediation path." },
  { id: "M3", sei: "absent", owner: "BBH",
    rec: "BBH-owned. Record the submission at send time — without that row, a submission that never reached SEI is indistinguishable from one that succeeded." },
  { id: "M21", sei: "absent", owner: "BBH",
    rec: "BBH-owned. Write the payload and its hash before the send, not after." },

  /* ---- Event Ingestion — absent from the pack by definition ---- */
  { id: "M1", sei: "absent", owner: "BBH",
    rec: "BBH-owned. Durable write, then commit the offset. The reverse order loses events with no trace." },
  { id: "M4", sei: "absent", owner: "BBH",
    rec: "BBH-owned. Delete must win over insert and update for the same key inside one micro-batch." },
  { id: "M5", sei: "absent", owner: "Joint",
    ask: "Does the view API offer as-of retrieval or only current state? And what are its rate limits, pagination and timeout behaviour?",
    rec: "As-of retrieval is the difference between replay reproducing the original load and replay quietly returning today's values. Ask before designing recovery." },
  { id: "M6", sei: "absent", owner: "BBH",
    rec: "BBH-owned. Array insert, one commit per micro-batch." },
  { id: "M7", sei: "absent", owner: "Joint",
    ask: "Confirm the domain dependency order, and whether a micro-batch can carry a fact whose dimension arrives in a later box.",
    rec: "Static ordering from the view field plus existing hold-and-replay. No dependency graph needed." },
  { id: "M10", sei: "absent", owner: "Joint",
    ask: "Are Event Hub sequence numbers monotonic per partition and gap-free under normal operation?",
    rec: "If yes, this is the strongest completeness proof in the estate and it costs almost nothing. Build it first." },
  { id: "M11", sei: "absent", owner: "Joint",
    ask: "Is there a published catalogue mapping eventid to domain and view? eventid is a type code, not a message identifier.",
    rec: "Without the catalogue, routing an event to the right view is inference rather than contract." },
  { id: "M12", sei: "absent", owner: "BBH",
    rec: "BBH-owned and nobody is writing it. Ship without enqueued_ts and sequence_number and lag and gap detection are not computable at all." },
  { id: "M13", sei: "absent", owner: "Joint",
    ask: "How many partitions does each domain topic have?",
    rec: "Without the denominator, 'every partition reported MB End' cannot be distinguished from 'the ones we happened to see'." },
  { id: "M14", sei: "absent", owner: "Joint",
    ask: "Is there a stable per-event identifier, or is (topic, partition, offset) the only identity available?",
    rec: "Two layers either way: offset uniqueness for replay, key-set collapse for producer retry. SEI assigns idempotency to the consumer in writing." },
  { id: "M15", sei: "absent", owner: "BBH",
    rec: "BBH-owned and the highest-value single addition. Without a dead-letter path a poison envelope stalls its partition permanently." },
  { id: "M16", sei: "absent", owner: "Joint",
    ask: "What is the expected interval between micro-batches per topic, and is it stable enough to baseline?",
    rec: "Lateness on a continuous stream comes from the stream's own rhythm. No expectation table needed if the cadence is stable." },

  /* ---- Processing ---- */
  { id: "13", sei: "covered", owner: "BBH",
    rec: "Leave it owning the standby path. Do not bolt an event mode onto a file ingestion framework; build the event chain beside it." },
  { id: "14", sei: "covered", owner: "BBH",
    rec: "Add MICROBATCH_ID. Free now, a change request after deployment." },
  { id: "15", sei: "partial", owner: "Joint",
    ask: "The pack's layer model is RAW to STG (a view) to INT to DIM and FACT. This design names Stage 2 Enriched and a Pre-Gold Exadata tier that the pack does not have. Which is the build target?",
    rec: "Reconcile the layer model before either document is treated as a spec. Then fix the STG view recomputation (B2)." },
  { id: "16", sei: "covered", owner: "SEI",
    ask: "RAW DDL is the schema contract and Gold runs on_schema_change='fail'. How is a column addition notified, with what lead time and what compatibility rule?",
    rec: "The most predictable future incident in the pack. M17 plus a written protocol closes it." },
  { id: "17", sei: "partial", owner: "SEI",
    ask: "What are the downstream semantics of op=D — soft close, delete, or tombstone? And what is the outbound correction protocol when BBH sent a wrong loader?",
    rec: "Component 17 predates events entirely. Both answers are needed before correction handling can be built." },

  /* ---- Data Quality ---- */
  { id: "23", sei: "covered", owner: "BBH",
    rec: "Keep for the standby path. M11 is its envelope equivalent." },
  { id: "24", sei: "covered", owner: "BBH",
    rec: "Set-level. Move to the EOD gate; per micro-batch it runs 288 times a day." },
  { id: "25", sei: "covered", owner: "BBH",
    rec: "Row-level and cheap. Safe to run per micro-batch." },
  { id: "26", sei: "covered", owner: "BBH",
    rec: "EOD gate only, and it is the gate's strongest check." },
  { id: "27", sei: "covered", owner: "BBH",
    rec: "Already daily and post-publish. Leave alone; do not move it per micro-batch for symmetry." },
  { id: "28", sei: "covered", owner: "BBH",
    rec: "Extend the taxonomy with event and outbound codes now, before they are invented ad hoc in three places." },
  { id: "M20", sei: "absent", owner: "SEI",
    ask: "Where are the loader validation rules authoritative — Data 360, or a specification BBH should hold? And which of them does SEI treat as blocking rather than advisory?",
    rec: "Build G6 against the template registry and make it blocking. An advisory outbound gate is the same as no gate." },
  { id: "M23", sei: "absent", owner: "SEI",
    ask: "Will SEI return accepted and rejected counts per submission, so sent-versus-accepted can be made to tie?",
    rec: "Without the counts, no outbound completeness claim is provable." },

  /* ---- Orchestration — full pass ---- */
  { id: "18", sei: "covered", owner: "BBH",
    rec: "C.1's three-task DAG is sound for one daily run. Size the scheduler and its metadata database for 288, or replace scheduled runs with a long-running consumer." },
  { id: "19", sei: "covered", owner: "BBH",
    rec: "Fully specified by the pack, and sound. Order conditionally on the collapsed key set so single-domain boxes pay nothing." },
  { id: "20", sei: "absent", owner: "Joint",
    ask: "The pack has a five-minute discovery loop but no intraday cadence model and no intraday SLA. Is there an intraday SLA, and what is 'behind' during the day?",
    rec: "Redefine this component around micro-batch cadence and consumer lag rather than a batch lane that runs more often." },
  { id: "21", sei: "partial", owner: "SEI",
    ask: "C.1's deterministic transform__<date> and D.4's restatement cannot both be satisfied — Airflow refuses a run that already succeeded, and C.1's reconciliation path only fires when no such run exists. How do both hold?",
    rec: "Answer that, then answer replay semantics under events. This is the component most damaged by the substitution." },
  { id: "22", sei: "partial", owner: "Joint",
    ask: "The policy covers partial file batches. What is the policy when three of five views pull successfully inside one micro-batch and the fourth times out?",
    rec: "Safe default is roll back whole; useful default is not. Somebody has to choose, and the choice belongs in this component." },
  { id: "M8", sei: "absent", owner: "Joint",
    ask: "E.2's completeness MINUS counts DAILY interfaces against ARCHIVED. Under events there is no interface to count and nothing reaches ARCHIVED. What replaces it?",
    rec: "Every micro-batch LOADED plus the EOD marker received. Marker-only gating lets the transformation run on short Stage 1 and the existing boundaries cannot see it." },
  { id: "M9", sei: "absent", owner: "SEI",
    ask: "What is the status API contract — endpoint, auth through Apigee, pagination, rate limits, whether a mid-processing poll returns partial errors, and how long reject detail stays retrievable?",
    rec: "The retention answer matters most: if detail is purged, BBH's stored copy becomes the system of record for outbound exceptions." },

  /* ---- Foundation — full pass ---- */
  { id: "29", sei: "covered", owner: "BBH",
    rec: "The pack specifies a file quarantine well. Extend it: an event dead-letter with a reason taxonomy, and an outbound quarantine for rejected records. Neither exists." },
  { id: "30", sei: "covered", owner: "BBH",
    rec: "RECON_RESULT's three boundaries are sound and all inbound-downstream. Add four event-side and five outbound. Nine missing boundaries is why loss in either direction is currently undetectable." },
  { id: "31", sei: "partial", owner: "SEI",
    ask: "RAW_*.FILE_REGISTRY_ID is still a proposal. Will it be accepted? Without it, tracing a row back to its delivering file degrades to business-date granularity.",
    rec: "Accept it, and state the event-path limit explicitly: because the pull re-reads current state, lineage runs Gold row to micro-batch to key and never to the change that caused it." },
  { id: "32", sei: "partial", owner: "SEI",
    ask: "A12 grants the loader DML on RAW and the registry, and DML-only on Gold. No consumer grant is described. Will a read-only role be added, and what is the approved masking policy for the 786 PII fields in SDC scope?",
    rec: "Add the read-only role to their security model rather than improvising it at connection time — which in practice means reusing the loader's account." },
  { id: "33", sei: "partial", owner: "Joint",
    ask: "FILE_SCHEMA_CONFIG covers file metadata. Where do the view catalogue, the eventid map and the interface calendar live?",
    rec: "Three new catalogues land here: M17, M18 and M19. Config, not code — an unknown value should raise, never be silently mapped." },
  { id: "34", sei: "partial", owner: "Joint",
    ask: "E.6 defines required context for four Splunk events; §8.1 lists thirteen. Nine have no payload contract, and none of the thirteen covers the event channel. Is that intended?",
    rec: "Define the nine, add the event-channel signals, and decide the rollup before the Splunk contract is written — thirteen signals times 288 cycles times domains is a different order of magnitude." },
  { id: "35", sei: "absent", owner: "BBH",
    rec: "BBH-owned and out of the pack's scope. §7 Status Monitoring Dashboard is SEI-side and is not this. Read-only, its own repository, second consumer of the shared inbox." },
  { id: "36", sei: "absent", owner: "BBH",
    rec: "BBH infrastructure. Nothing to ask SEI." },
  { id: "M17", sei: "absent", owner: "SEI",
    ask: "There is no schema-change protocol anywhere in the pack. How is a change notified, with what lead time, and what is the backward-compatibility rule?",
    rec: "Two individually sound decisions — RAW DDL as the contract, and on_schema_change='fail' — are jointly a production incident with no owner. This registry is the guard." },
  { id: "M18", sei: "absent", owner: "Joint",
    ask: "EXPECTED_INTERFACE_CALENDAR and REQUIRED_IND are still proposals. Will they be accepted, and what is each interface's cadence and holiday calendar?",
    rec: "The single largest dependency in the P list. Without it, 'what was expected today' is wrong every weekend and holiday, and false missing interfaces are worse than no report." },
  { id: "M19", sei: "absent", owner: "SEI",
    ask: "The loader templates live in Data 360, not in the design pack. How is a template version change communicated, and how long are two versions supported? The catalogue shows v1.24, v1.21 and v9 live together.",
    rec: "Pin the version in force at generation onto every submission, or an error returned next week cannot be read against the template that produced it." },
  { id: "M22", sei: "absent", owner: "SEI",
    ask: "What is the correction protocol for a loader BBH sent wrongly? Does a corrected submission reference the original, and does SEI supersede or duplicate?",
    rec: "Model retry and correction as different operations. A retry reuses the submission id; a correction is a new submission carrying corrects_submission_id." },

  /* ---- Platform ---- */
  { id: "55", sei: "absent", owner: "BBH",
    rec: "BBH-owned. Bound the pool per pod and the pods per micro-batch; an unbounded fan-out against a shared Oracle takes down another team's service." },
  { id: "62", sei: "absent", owner: "Joint",
    ask: "What is Event Hub retention? Under events it is the replay window and therefore the RTO, and it is unstated.",
    rec: "State retention first, then derive RPO and RTO from it. The pack has no DR section at all — D.1 to D.6 are data correction, not disaster recovery." },
];

/* Plane-level verdict for the two planes under review */
export const AR_PLANE_REC = {
  ORCH: {
    title: "Orchestration",
    has: "C.1 specifies the DAG well: three tasks, dynamic task mapping, a deterministic run id, a guarded PENDING to TRIGGER transition, and dim-before-fact with hold-and-replay. For one daily file cycle this is a complete and careful design.",
    lacks: "It assumes a discrete 'everything has arrived' moment. Events never produce one. There is no intraday cadence model, no intraday SLA, no gate that works without interfaces to count, no partial-view policy inside a micro-batch, and no poller for the return leg. Replay is worse than missing — it is specified in terms the event path cannot honour.",
    rec: "Do not extend the daily DAG to run 288 times. Separate the two clocks: a long-running consumer owning the intraday path, and the existing DAG owning the EOD transformation, meeting at a gate that requires every micro-batch LOADED. Answer the transform__<date> versus restatement collision before anything else here is built.",
    verdict: "2 of 7 specified · 2 partly · 3 absent",
  },
  FND: {
    title: "Foundation",
    has: "Quarantine, reconciliation and the configuration store are all genuinely specified — FILE_REGISTRY's lifecycle, dq_validation_failure with resolution_status and reprocess_eligible, RECON_RESULT's three boundaries, FILE_SCHEMA_CONFIG. The error and recovery thinking in D.1 to D.6 is the strongest part of the whole pack.",
    lacks: "Every one of them is inbound and file-shaped. No event dead-letter, no outbound quarantine, nine reconciliation boundaries missing, no schema contract, no expectation model, no loader template registry, no read-only grant, no PII classification, and nine of thirteen Splunk signals with no payload contract. Lineage also degrades permanently under events and the pack does not say so.",
    rec: "Foundation is where the substitution costs most, because every one of its components is estate-wide. Extend rather than duplicate: one quarantine with an event and an outbound reason taxonomy, one reconciliation framework with twelve boundaries instead of three, one configuration store holding the three new catalogues. Resist building a parallel event-side foundation.",
    verdict: "2 of 12 specified · 4 partly · 6 absent",
  },
};

/* ------------------------------------------------------------------ *
 * Externalising the Stage 2 to Gold transformation rules              *
 * ------------------------------------------------------------------ */
export const AR_RULE_EXTERNALISATION = {
  title: "Stage 2 \u2192 Gold: externalise the rules so a BA owns them",
  problem:
    "Every mapping and derivation between Stage 2 and Gold is hand-written dbt SQL. A change to what a " +
    "column means is therefore a code change, a pull request and a release. The people who own the business " +
    "meaning cannot change it; the people who can change it do not own the meaning. That gap is where wrong " +
    "numbers come from, and it gets worse as the mapping surface grows.",
  principle:
    "Externalise the rules, not the engine. Generate dbt from them; never interpret them at run time.",
  owns: [
    ["BA owns", "#159943", "Source column to target column mapping \u00b7 code and value translations \u00b7 derived expressions and their conditions \u00b7 defaults \u00b7 which attributes are SCD-tracked \u00b7 the rule's business description"],
    ["Engineering owns", "#0b5e83", "Join strategy \u00b7 incremental predicates \u00b7 merge keys \u00b7 partitioning \u00b7 SCD2 close and open mechanics \u00b7 dim-before-fact ordering \u00b7 hold-and-replay"],
  ],
  rules: [
    { name: "TRANSFORM_RULESET", grain: "one row per target model per version",
      cols: "TARGET_MODEL \u00b7 VERSION \u00b7 STATUS \u00b7 EFFECTIVE_FROM / TO \u00b7 APPROVED_BY \u00b7 APPROVED_TS",
      note: "Never updated in place \u2014 superseded. A ruleset that produced a row must stay readable for as long as that row is explainable." },
    { name: "TRANSFORM_RULE", grain: "one row per target column per ruleset",
      cols: "RULESET_ID \u00b7 SEQ \u00b7 TARGET_COLUMN \u00b7 RULE_TYPE \u00b7 SOURCE_EXPRESSION \u00b7 CONDITION \u00b7 DEFAULT_VALUE \u00b7 BUSINESS_DESCRIPTION",
      note: "RULE_TYPE is a closed set: DIRECT, CONSTANT, LOOKUP, DERIVED_EXPR, CONDITIONAL, AGGREGATE. An open expression language is how a rule registry becomes a second programming language nobody can review." },
    { name: "TRANSFORM_LOOKUP", grain: "one row per source value per domain per version",
      cols: "LOOKUP_DOMAIN \u00b7 SOURCE_VALUE \u00b7 TARGET_VALUE \u00b7 EFFECTIVE_FROM / TO",
      note: "The classic BA-owned artefact, and the one most often kept in a spreadsheet today. An unmapped source value raises; it never passes through or defaults silently." },
    { name: "TRANSFORM_RULE_TEST", grain: "one row per expectation",
      cols: "RULE_ID \u00b7 INPUT_JSON \u00b7 EXPECTED_VALUE \u00b7 LAST_RUN_TS \u00b7 LAST_RESULT",
      note: "At least one per rule, run in CI on every regeneration. Without it, externalisation means more people able to ship a wrong number rather than fewer." },
  ],
  flow: [
    ["1", "BA edits a rule", "Authoring surface writes to the registry as a draft ruleset. Nothing downstream moves."],
    ["2", "Approval", "STATUS_TRANSITION marks the draft-to-active move as REQUIRES_APPROVAL. A derivation on fact_transactions is a change to the firm's books, and four eyes is the control."],
    ["3", "Compile", "CI regenerates the dbt models from the approved ruleset. The generated SQL lands in a pull request as a diff \u2014 the BA's change made reviewable in engineering's own terms."],
    ["4", "Test", "Rule expectations run against the generated SQL, alongside the existing dbt tests."],
    ["5", "Run", "An ordinary dbt run. Lineage, tests and documentation all still work, because the output is dbt and not an interpreter."],
    ["6", "Stamp", "Every Gold row carries RULE_SET_VERSION. Three months later the number is explainable without archaeology in the commit log."],
  ],
  risk:
    "Externalised without effective dating, generated SQL and CI tests, this produces a system where more " +
    "people can change logic and nobody can explain a number \u2014 strictly worse than hard-coded SQL. The " +
    "three guardrails are not refinements to add later; they are what makes the idea safe at all.",
  scope:
    "Stage 2 to Gold only. Do not extend it to Stage 1 ingestion, where the RAW DDL is the contract and there " +
    "is no business logic to own, and do not let it absorb the correctness machinery \u2014 SCD2 mechanics, merge " +
    "semantics and hold-and-replay stay in code.",
};
