// CP Integration Hub — independent architect review.
//
// Standpoint: data architect for a high-throughput, high-error-tolerance
// integration platform. One assumption changes: SDC events are the primary
// ingestion path. Everything from Stage 1 onward is taken exactly as the SEI
// design pack specifies it (File Ingestion Framework TDD v2.0, dbt
// Transformation TDD v2, Architecture v5).
//
// The pack was written for a file-driven pipeline. This file records what
// that one substitution breaks, what it makes expensive, and what it leaves
// with no owner. Findings are keyed to the tracker component ids in
// seiDesignTracker.js so every observation lands on something real.

export const AR_SUMMARY = {
  title: "Architect review — events-primary Integration Hub",
  line:
    "One assumption substituted: SDC events replace files as the primary ingestion path. " +
    "Stage 1 onward is unchanged from the SEI pack. 18 components are missing, 10 bottlenecks " +
    "appear that a daily file cycle never had, and 12 error paths have no owner.",
  counts: { missing: 18, bottlenecks: 10, errors: 12, mapped: 25, unchanged: 40 },
};

/* ------------------------------------------------------------------ *
 * The assumption set                                                  *
 * ------------------------------------------------------------------ */
export const AR_ASSUMPTIONS = [
  { id: "A1", holds: "changed", what: "SDC events are the primary ingestion path",
    detail: "All intraday and EOD data arrives as events. Files remain as a daily standby that is generated and held, not loaded.",
    src: "BBH decision, post-dates the pack" },
  { id: "A2", holds: "changed", what: "The envelope carries four fields and no data",
    detail: "eventid (a type code, not a message id), key, op (I/U/D), view. The event says a row changed; it never says what changed. A pull re-reads current state from the named view.",
    src: "SDC Events Structure" },
  { id: "A3", holds: "changed", what: "Micro-batch boxing on every partition of every topic",
    detail: "MB Start (1000) and MB End (1001) bracket each box, written to every partition of every domain topic. One micro-batch is one commit. Empty micro-batches are normal and complete.",
    src: "Domain Partitions — Micro Batch Boxing Pattern" },
  { id: "A4", holds: "changed", what: "At-least-once delivery, ordered within topic+partition only",
    detail: "No global ordering, no cross-topic ordering. SEI guarantees delivery and boxing; the consumer owns everything else.",
    src: "SEI producer/consumer contract" },
  { id: "A5", holds: "changed", what: "The consumer owns idempotency and cross-domain dependency",
    detail: "SEI states both explicitly as consumer responsibilities. Neither has a component in the 65.",
    src: "SEI producer/consumer contract" },
  { id: "A6", holds: "unchanged", what: "Medallion shape and the control plane",
    detail: "SWP_RAW (Bronze) → STG (a view, recomputed on read) → INT (Silver, PK = natural key + BUSINESS_DATE, 7-day retention) → DIM then FACT (Gold, DML-only MERGE, on_schema_change='fail'). DATE_CONTROL, FILE_REGISTRY, RECON_RESULT, DQ_VALIDATION_FAILURE as specified.",
    src: "dbt Transformation TDD v2 / File Ingestion TDD v2.0" },
  { id: "A7", holds: "unchanged", what: "Splunk is a write-only sink; verdicts are not stored in Oracle",
    detail: "E.6 forbids SLA_STATUS, SLA_BREACH_IND and ALERT_SENT_IND on DATE_CONTROL. PASS/WARNING is derived, never persisted.",
    src: "File Ingestion TDD v2.0 E.6, dbt TDD B.5" },
  { id: "A8", holds: "unchanged", what: "Airflow 3.0 on OpenShift, Oracle as the control store",
    detail: "Dynamic task mapping, deterministic run ids, guarded state transitions, worker pods per work item.",
    src: "File Ingestion TDD v2.0 C.1" },
];

/* ------------------------------------------------------------------ *
 * Components that do not exist in the 65                              *
 * ------------------------------------------------------------------ */
export const AR_MISSING = [
  // --- Ingress ---
  { id: "M1", plane: "Ingress/Egress", name: "SDC Event Listener", pri: "P1", build: "High",
    tech: "Python · Event Hub consumer",
    deliverable: "Consumer group per domain topic; durable write then offset commit",
    perf: "Throughput ceiling is partition count × one consumer per partition. Partition count is unstated, so the ceiling is unknown and unprovable.",
    err: "Offset must be committed only after the durable write. The reverse order loses events silently on a crash — the single most damaging ordering mistake available here.",
    why: "There is no component between SEI publishing and Stage 1 holding rows. Components 8 and 9 are file sensors." },
  { id: "M2", plane: "Ingress/Egress", name: "Callback Receiver", pri: "P1", build: "Medium",
    tech: "Python · Apigee-fronted endpoint",
    deliverable: "Authenticate, validate envelope shape, durable write, 202",
    perf: "Must not do correlation work inline. Parsing and matching belong downstream of the acknowledgement.",
    err: "Acknowledge on durable write, never on successful processing. A 500 because a lookup failed ties SEI's retry behaviour to BBH's internal bugs.",
    why: "SEI pushes loader status. Component 10 covers producing outbound payloads, nothing receives." },
  { id: "M3", plane: "Ingress/Egress", name: "Loader Submission Registry", pri: "P1", build: "High",
    tech: "Oracle DDL + Python",
    deliverable: "LOADER_SUBMISSION · LOADER_STATUS_HISTORY (with SOURCE) · LOADER_ERROR",
    perf: "Error detail is fetched once on reaching terminal-with-errors, paginated and stored. Re-fetching per poll pulls the same rejected records repeatedly.",
    err: "Without a row written at send time, a submission that never reached SEI is indistinguishable from one that succeeded. Silence looks exactly like success.",
    why: "The outbound path has no FILE_REGISTRY equivalent anywhere in the pack or the 65." },

  // --- Processing ---
  { id: "M4", plane: "Processing", name: "Key-Set Collapser", pri: "P1", build: "High",
    tech: "Python",
    deliverable: "Per micro-batch, per view: one distinct key set with op precedence",
    perf: "This component decides the entire cost model. Collapsing 50,000 events to 8,000 distinct keys is the difference between one query and fifty thousand.",
    err: "D must win over I and U for the same key inside one micro-batch, or a deleted row is re-pulled and resurrected. Unknown view or unknown op needs a disposition, not a crash.",
    why: "Nothing in the pack collapses anything; the file path has no equivalent problem." },
  { id: "M5", plane: "Processing", name: "Set-Based Puller", pri: "P1", build: "High",
    tech: "Python · SEI view API",
    deliverable: "One bound, set-based retrieval per view per micro-batch",
    perf: "The system's throughput ceiling. Oracle's 1000-element IN limit forces a global temporary table or array bind with a join — an IN list built by string concatenation will fail in production and silently truncate in test.",
    err: "Needs a circuit breaker. If SEI's view API degrades, retrying every micro-batch amplifies load against an already failing dependency.",
    why: "Per-event retrieval is the default anyone reaches for and it is ruinous — see bottleneck B1." },
  { id: "M6", plane: "Processing", name: "Intraday Stage-1 Loader", pri: "P1", build: "Medium",
    tech: "Python · Oracle array insert",
    deliverable: "Continuous micro-batch load into Stage 1 with one commit per micro-batch",
    perf: "Array insert with a tuned batch size, one commit per micro-batch. Row-by-row insert and per-row commit is the classic first wall and it arrives early.",
    err: "A failed micro-batch rolls back whole. A partially loaded micro-batch marked LOADED is the defect that makes the EOD gate lie.",
    why: "Component 13 is a file ingestion framework. The event path loads continuously, not once a day." },

  // --- Orchestration ---
  { id: "M7", plane: "Orchestration", name: "Domain Sequencer", pri: "P1", build: "Medium",
    tech: "Python · Airflow",
    deliverable: "Static ordering End Client → Account → Transaction, derived from the view field",
    perf: "Serialises what could run in parallel. Only serialise when a micro-batch actually contains both domains; otherwise the ordering cost is paid 288 times a day for nothing.",
    err: "A dimension event in a later micro-batch than its fact falls to hold-and-replay, and the 7-day cliff starts ticking from that moment.",
    why: "SEI assigns cross-domain dependency to the consumer. No component owns it." },
  { id: "M8", plane: "Orchestration", name: "Event Gate Evaluator", pri: "P1", build: "Medium",
    tech: "Python · Oracle",
    deliverable: "Replaces E.2's MINUS: every micro-batch LOADED, plus the EOD marker received",
    perf: "Trivial to compute. Its cost is entirely in being wrong.",
    err: "Gating on the marker alone lets the transformation run on short Stage 1 — and STG→INT still reconciles, because it ties against a Stage 1 that is itself short.",
    why: "E.2 counts DAILY interfaces MINUS ARCHIVED. Under events there is no interface to count and nothing reaches ARCHIVED." },
  { id: "M9", plane: "Orchestration", name: "SEI Status Poller", pri: "P2", build: "Medium",
    tech: "Python · Airflow · Apigee",
    deliverable: "Non-terminal submissions only, tiered cadence, detail fetch on terminal",
    perf: "Terminal submissions must drop out of the poll set, or Apigee call volume grows with history rather than with work in flight.",
    err: "A submission past max age becomes STATUS_UNRESOLVED rather than sitting at SUBMITTED for ever. When push and poll disagree, the poll wins and terminal never regresses.",
    why: "The backstop for a notification that never arrives. Nothing in the 65 calls SEI for status." },

  // --- Data Quality ---
  { id: "M10", plane: "Data Quality", name: "Sequence Gap Detector", pri: "P1", build: "Medium",
    tech: "Python · SQL",
    deliverable: "Monotonic sequence numbers per partition; a gap is a provably lost event",
    perf: "One ordered scan per partition per micro-batch. Cheap.",
    err: "This is the strongest completeness proof in the whole estate and it currently has no owner. The file channel has nothing comparable.",
    why: "Absent from the pack and from the 65, despite costing almost nothing." },
  { id: "M11", plane: "Data Quality", name: "G0 Envelope Gate", pri: "P1", build: "Medium",
    tech: "Python",
    deliverable: "Per-envelope structural validation before staging",
    perf: "Must run in the consumer loop, so it has to be O(1) per envelope with no database lookup.",
    err: "Unknown eventid, unresolvable view, invalid op, missing key. Each needs a disposition. Without a dead-letter path a single poison envelope stalls its partition for ever.",
    why: "G1 validates a file's structure. Nothing validates an envelope." },

  // --- Foundation ---
  { id: "M12", plane: "Foundation", name: "Event Staging Store", pri: "P1", build: "High",
    tech: "Oracle DDL",
    deliverable: "(topic, partition, offset, sequence_number, enqueued_ts, eventid, key, op, view)",
    perf: "The unique index on (topic, partition, offset) sits on the hot insert path. Range-partition by business date with local indexes, or the index becomes the bottleneck rather than the guard.",
    err: "This is layer one of idempotency: a consumer replay yields the same offset and is rejected by the constraint.",
    why: "Entirely BBH-owned and nobody is writing it. Ship it without enqueued_ts and sequence_number and lag and gap detection are not computable at all." },
  { id: "M13", plane: "Foundation", name: "Micro-Batch Registry", pri: "P1", build: "High",
    tech: "Oracle DDL + Python",
    deliverable: "(topic, partition, mb_id) with state, counts and both box timestamps",
    perf: "Small table, high update rate. One row per partition per micro-batch per topic — at a five-minute cadence that is still tens of thousands of rows a day.",
    err: "A start with no end, or a partition that never reported, is the only way to see a stalled producer. Without the partition count as a denominator, 'all partitions reported' is unprovable.",
    why: "The event channel's FILE_REGISTRY. It does not exist." },
  { id: "M14", plane: "Foundation", name: "Idempotency Service", pri: "P1", build: "High",
    tech: "Python · Oracle",
    deliverable: "Two layers: offset uniqueness, then key-set collapse per view per micro-batch",
    perf: "Layer one is an index write. Layer two is free — it falls out of M4.",
    err: "A producer retry arrives at a different offset with identical content, so layer one cannot see it. Only collapsing to a distinct key set neutralises it.",
    why: "SEI assigns idempotency to the consumer in writing. No component accepts it." },
  { id: "M15", plane: "Foundation", name: "Event Quarantine", pri: "P1", build: "High",
    tech: "Oracle DDL + Python",
    deliverable: "Dead-letter with a reason taxonomy and a bounded replay counter",
    perf: "n/a",
    err: "A file that fails becomes QUARANTINED. An event that fails has nowhere to go. Reasons needed: unknown view, invalid op, key not found, pull timeout, unparseable envelope, sequencer cycle.",
    why: "Component 29 is a file quarantine. The event path has no equivalent and therefore no poison-pill escape." },
  { id: "M16", plane: "Foundation", name: "Consumer Lag Monitor", pri: "P1", build: "Low",
    tech: "Python · Splunk",
    deliverable: "Per-partition lag from broker enqueue metadata",
    perf: "n/a",
    err: "Lag is the only intraday health signal there is. The envelope carries no timestamp of its own, so lag must come from broker metadata captured at receipt — which is why M12 needs enqueued_ts.",
    why: "Component 34 Observability predates events and has no lag concept." },
  { id: "M17", plane: "Foundation", name: "Schema Contract Registry", pri: "P1", build: "Medium",
    tech: "Oracle DDL + CI",
    deliverable: "Per-view column contract, versioned, checked before the pull is trusted",
    perf: "One cached read per view per run.",
    err: "FILE_SCHEMA_CONFIG holds no column mapping, so RAW DDL is the schema contract, while Gold runs on_schema_change='fail'. A column added upstream breaks the pipeline by design with no notification path. This component is the guard.",
    why: "The most predictable future incident in the pack, and nothing watches for it." },
  { id: "M18", plane: "Foundation", name: "Expectation Store", pri: "P1", build: "Medium",
    tech: "Oracle DDL",
    deliverable: "Interface calendar, loader cadence, marker schedule, event cadence baseline",
    perf: "n/a",
    err: "Without it nothing can be late, only absent. On the event channel lateness is derivable from the stream's own rhythm; on every other channel it needs a stated expectation.",
    why: "EXPECTED_INTERFACE_CALENDAR and REQUIRED_IND are still proposals, and no channel has an expectation model." },
];

/* ------------------------------------------------------------------ *
 * Performance bottlenecks                                             *
 * ------------------------------------------------------------------ */
export const AR_BOTTLENECKS = [
  { id: "B1", sev: "critical", title: "The pull is the system's throughput ceiling",
    comp: ["M5", "M4"],
    body: "Query count is driven by cadence × views, not by account count. A five-minute cadence is 288 cycles a day; the reference client ran 17,955 queries a month, about 2.08 per cycle. Ten views at the same cadence is roughly 86,000 queries a month. Scaling the estimate by accounts understates it badly, because accounts do not appear in the formula.",
    fix: "One set-based query per view per micro-batch, bound to a collapsed key set. Never one query per event. Oracle's 1000-element IN limit means a global temporary table or an array bind with a join — a concatenated IN list fails in production and truncates silently in test." },

  { id: "B2", sev: "critical", title: "STG is a view, and events make it run 288 times a day",
    comp: ["15", "M6"],
    body: "The dbt TDD defines STG as a view, recomputed on read. Under a daily file cycle it is recomputed once. Under intraday events, INT is built incrementally all day, so the STG view is recomputed on every incremental run — and each recomputation scans Stage 1. This is the single largest cost the event substitution introduces, and it comes from a design decision that was entirely reasonable when it was made.",
    fix: "Either materialise STG per micro-batch, or ensure the INT incremental predicate pushes down to Stage 1's partition so the view scans one micro-batch rather than the whole accumulated day. Verify the push-down on the actual plan; do not assume it." },

  { id: "B3", sev: "high", title: "Airflow task volume multiplies by roughly 300×",
    comp: ["18", "51"],
    body: "The scheduler polls its metadata database continuously and uses SELECT FOR UPDATE in its loop. Moving from about one DAG run a day to 288 intraday runs, each with per-domain dynamic task mapping, multiplies task_instance rows by two to three orders of magnitude. Nothing in the pack has costed the scheduler itself.",
    fix: "Size the scheduler and its database for the new task rate before build, set an aggressive metadata retention policy, and consider one long-running consumer rather than 288 scheduled DAG runs." },

  { id: "B4", sev: "high", title: "Event staging insert rate",
    comp: ["M12", "M6"],
    body: "A Python consumer writing envelope rows one at a time is the first wall every event pipeline hits. The unique index on (topic, partition, offset) sits directly on the hot insert path, so the guard that gives idempotency is also the thing that slows the write.",
    fix: "Array insert with a tuned batch size and one commit per micro-batch. Range-partition the staging table by business date with local indexes so index maintenance stays inside the current partition." },

  { id: "B5", sev: "high", title: "DQ gates were designed per file, not per micro-batch",
    comp: ["23", "24", "26", "27"],
    body: "G2 profiling, G4 tie-out and G5 post-publish recon are set-level aggregates. Running them per micro-batch means 288 full aggregate passes a day. Running them only daily means an intraday defect is invisible until the gate.",
    fix: "Split by cost class: G0 and G1 and G3 per micro-batch because they are row-level and cheap; G2, G4 and G5 at the EOD gate because they are set-level and expensive. State the split rather than leaving it to whoever writes the DAG." },

  { id: "B6", sev: "high", title: "INT's incremental MERGE into a growing current-day partition",
    comp: ["15", "M6"],
    body: "INT is partitioned by BUSINESS_DATE with a 7-day window. Under intraday events the current day's partition is written to continuously, and an incremental MERGE against a partition that grows all day degrades as the day goes on. The 6pm micro-batch is materially slower than the 6am one.",
    fix: "Subpartition by micro-batch, or load append-only with a late dedupe at the gate. Measure the degradation curve before choosing; it may be acceptable at real volumes, but nobody knows the real volumes." },

  { id: "B7", sev: "medium", title: "Oracle session concurrency under intraday fan-out",
    comp: ["55", "18"],
    body: "Connection pooling was sized for a daily per-domain fan-out. Intraday micro-batches multiply concurrent sessions by the cadence, and Airflow dynamic task mapping spawns a worker pod per work item, each opening its own connections.",
    fix: "Bound the pool per pod and the pod count per micro-batch. An unbounded fan-out against a shared Oracle is how one pipeline takes down another team's service." },

  { id: "B8", sev: "medium", title: "DIM-before-FACT serialisation is now paid per micro-batch",
    comp: ["19", "M7"],
    body: "Under a daily batch the ordering cost is paid once. Under intraday it is paid 288 times, including on the many micro-batches that contain only one domain and need no ordering at all.",
    fix: "Serialise only when the micro-batch actually contains both domains. Inspect the collapsed key set before choosing the execution shape." },

  { id: "B9", sev: "medium", title: "Splunk ingest volume",
    comp: ["34", "M16"],
    body: "Thirteen operational signals, multiplied by 288 cycles and by domain, is a different order of magnitude from a daily file pipeline. Splunk ingest is metered and rate limited.",
    fix: "Emit per micro-batch only what is actionable; aggregate the rest to a per-cycle or per-hour rollup. Decide this before the contract is written, not after the first bill." },

  { id: "B10", sev: "medium", title: "Pull latency is inside the micro-batch's critical path",
    comp: ["M5", "M6"],
    body: "The box is not complete until every view has been pulled and loaded. A single slow view holds the whole micro-batch, and the next micro-batch is already arriving. Queueing under a fixed cadence is how a small latency regression becomes an unbounded backlog.",
    fix: "Bound the pull with a timeout and an explicit partial disposition, and monitor the ratio of micro-batch duration to cadence interval. Above roughly 0.7 the system has no recovery headroom left." },
];

/* ------------------------------------------------------------------ *
 * Error paths with no owner                                           *
 * ------------------------------------------------------------------ */
export const AR_ERRORS = [
  { id: "E1", sev: "critical", title: "Offset committed before the durable write",
    comp: ["M1", "M12"],
    body: "If the consumer commits its offset and then crashes before the staging write lands, those events are gone and nothing records that they existed. The loss is silent and permanent — there is no gap to detect, because the sequence numbers were never stored.",
    owner: "Nothing in the pack states the ordering. Write, then commit." },
  { id: "E2", sev: "critical", title: "Poison envelope stalls a partition indefinitely",
    comp: ["M11", "M15"],
    body: "Ordering is guaranteed within a partition, so a single unprocessable envelope blocks everything behind it until a human intervenes. At-least-once redelivery means it returns for ever.",
    owner: "No dead-letter path exists for events. Component 29 quarantines files." },
  { id: "E3", sev: "critical", title: "Replay does not reproduce the original load",
    comp: ["21", "M5"],
    body: "The file path replays identical bytes and gets an identical result. The event pull re-reads current state, so replaying yesterday's micro-batch today returns today's values. The recovery procedures in D.1 to D.6 are written entirely in file terms and do not survive the substitution.",
    owner: "Either store the pulled payload, or obtain as-of retrieval from SEI. Neither is specified." },
  { id: "E4", sev: "critical", title: "The gate cannot detect event loss",
    comp: ["M8", "30"],
    body: "A micro-batch that fails at 11am and goes unnoticed means the EOD transformation runs on short Stage 1 — and STG→INT reconciles cleanly, because it ties against a Stage 1 that is itself short. The existing three boundaries are all downstream of the loss and cannot see it.",
    owner: "Requires the four event-side boundaries and a gate that demands every micro-batch LOADED." },
  { id: "E5", sev: "high", title: "Not-found key on pull has no disposition",
    comp: ["M5", "28"],
    body: "The key changed and by the time the pull runs the row is gone — a delete race, and at low rates entirely normal. At high rates it is a symptom of something serious. Treating it as an error alarms constantly; treating it as normal hides real loss.",
    owner: "Needs a rate threshold tied to the observed delete rate, not a binary rule." },
  { id: "E6", sev: "high", title: "Partial micro-batch failure across views",
    comp: ["22", "M6"],
    body: "If three of five views pull successfully and the fourth times out, is the micro-batch FAILED and rolled back whole, or PARTIAL and advanced? Component 22 sets a partial-batch policy for files and says nothing about views inside a box.",
    owner: "Unowned. The safe default is roll back whole; the useful default is not, and somebody has to choose." },
  { id: "E7", sev: "high", title: "Consumer rebalance in the middle of a box",
    comp: ["M1", "M13"],
    body: "A group rebalance mid-micro-batch moves a partition to a different consumer, so MB Start and MB End for that partition land on different processes with different in-memory state.",
    owner: "Nothing coordinates a box across a rebalance. The registry has to be the coordination point, not process memory." },
  { id: "E8", sev: "high", title: "No circuit breaker on the SEI view API",
    comp: ["M5"],
    body: "If SEI's retrieval degrades, every micro-batch retries against an already failing dependency and amplifies the load. The classic retry storm, with a fixed cadence guaranteeing it repeats.",
    owner: "Needs a breaker with backoff and an explicit degraded mode that stops pulling and keeps staging." },
  { id: "E9", sev: "high", title: "op = D semantics are undefined downstream",
    comp: ["17", "M4"],
    body: "A delete event names a key whose row no longer exists to pull. Correction Handling is written for restatement and in-place merge, not for a delete arriving as an event. Whether a delete soft-closes the INT row, removes it, or writes a tombstone is unstated.",
    owner: "Component 17 predates events entirely." },
  { id: "E10", sev: "medium", title: "Replay has no attempt limit",
    comp: ["21", "M15"],
    body: "The Replay / Rerun Engine has no maximum attempt count before a work item is quarantined. A permanently failing item retries for ever and consumes capacity every cycle.",
    owner: "Bounded retry plus quarantine. Trivial to add now, painful to retrofit." },
  { id: "E11", sev: "medium", title: "Outbound has no error model at all",
    comp: ["10", "M3"],
    body: "Loader submissions have no registry, no status history, no error store and no correction protocol. A retry reuses the submission id; a correction is a new submission that references the one it corrects. Neither is defined.",
    owner: "The whole outbound half of the estate." },
  { id: "E12", sev: "medium", title: "Dimension arriving after fact starts the 7-day clock",
    comp: ["M7", "17"],
    body: "Hold-and-replay handles a fact whose dimension has not arrived, marking MISSING_DIMENSION_KEY with reprocess_eligible. But INT retains seven days, so a dimension that arrives on day eight means the held fact is silently gone from FACT for ever.",
    owner: "The cliff is real and nothing surfaces days-to-expiry on held rows." },
];

/* ------------------------------------------------------------------ *
 * Findings mapped onto the existing 65                                *
 * ------------------------------------------------------------------ */
export const AR_FINDINGS = [
  { id: "8", verdict: "demoted", name: "Landing Zone + Transport",
    finding: "Becomes the standby path. It also conflicts with the SEI pack: this design uses a manifest written last plus deferrable sensors verifying size and mtime, while the File Ingestion TDD discovers by filename pattern every five minutes with no manifest at all. Two different transport contracts with the same upstream party.",
    action: "Pick one contract. The manifest protocol is stronger; the TDD is what is being built." },
  { id: "9", verdict: "demoted", name: "File Arrival Sensors",
    finding: "Deferrable sensors idling all day for a path that now only needs to prove a file was generated and held. The registry gains no state meaning 'available and deliberately unused', so a standby file looks either permanently missing or falsely satisfies a gate that should not be running.",
    action: "Add the state. Reduce the sensor to a readiness check." },
  { id: "10", verdict: "gap", name: "Outbound Producers",
    finding: "Covers generating and sending. Nothing receives status, nothing polls for detail, nothing records the submission. Three missing components hang off this one.",
    action: "M2, M3 and M9." },
  { id: "13", verdict: "rebuild", name: "Python Ingestion Framework",
    finding: "Written as a file ingestion framework: discover work items, process a file, evaluate completeness. The event path shares none of that shape — it consumes continuously, collapses, pulls and loads per micro-batch.",
    action: "Do not extend this component with an event mode. Build M1, M4, M5 and M6 alongside it and let this one own the standby path." },
  { id: "14", verdict: "amend", name: "Stage 1 RAW",
    finding: "Needs a micro-batch identifier column to make a load traceable to its box, and a commit boundary of one micro-batch. Without the column, lineage from a Gold row stops at the business date.",
    action: "Add MICROBATCH_ID. Free now, a change request later." },
  { id: "15", verdict: "bottleneck", name: "Stage 2 Enriched (dbt)",
    finding: "Two problems. This design names a Pre-Gold Exadata tier and an Enriched layer that the SEI pack does not have; the pack has STG as a view and INT as Silver. And the STG view is recomputed on every incremental run, which events turn from once a day into 288 times a day.",
    action: "Reconcile the layer model first, then B2." },
  { id: "16", verdict: "risk", name: "Gold (dbt)",
    finding: "on_schema_change='fail' with DML-only MERGE. Correct for safety, and it means an upstream column addition halts the pipeline with no notification path and no forward fix that is not a deploy.",
    action: "M17, plus a stated schema-change protocol with SEI." },
  { id: "17", verdict: "gap", name: "Correction Handling",
    finding: "Written for restatement and in-place merge. A delete arriving as an event has no defined downstream behaviour, and an outbound correction — a new submission referencing the one it corrects — is not modelled at all.",
    action: "Define op=D semantics and the outbound correction protocol." },
  { id: "18", verdict: "bottleneck", name: "Airflow DAG + Per-Domain Fan-out",
    finding: "Task volume multiplies by roughly 300× under intraday micro-batches with dynamic task mapping.",
    action: "B3. Consider a long-running consumer instead of 288 scheduled runs." },
  { id: "19", verdict: "bottleneck", name: "Dim-before-Fact / dbt Threads",
    finding: "The ordering cost moves from once a day to once per micro-batch, including on boxes containing a single domain.",
    action: "B8 — order conditionally on the collapsed key set." },
  { id: "20", verdict: "rebuild", name: "Intraday Cadence Control",
    finding: "The one component that anticipated intraday, but defined as a batch lane running more often. Event cadence is not a schedule — it is the stream's own rhythm, and lateness comes from a rolling baseline of the inter-micro-batch interval.",
    action: "Redefine around micro-batch cadence and consumer lag." },
  { id: "21", verdict: "broken", name: "Replay / Rerun Engine",
    finding: "Its core assumption does not survive events. Replaying a micro-batch re-reads current state and returns today's values, not the values as of the original event. It also has no maximum attempt count.",
    action: "E3 and E10. This is the component most damaged by the substitution." },
  { id: "22", verdict: "gap", name: "Partial-Batch Policy",
    finding: "Sets policy for partial file batches. Silent on partial view failure inside a micro-batch, which is the equivalent case and the more frequent one.",
    action: "E6." },
  { id: "23", verdict: "amend", name: "G1 File / Structural Gate",
    finding: "Validates a file's structure. Nothing validates an envelope, so an unknown view or invalid op reaches the collapser.",
    action: "M11, and keep G1 for the standby path." },
  { id: "24", verdict: "bottleneck", name: "G2 RAW Profiling Gate",
    finding: "A set-level aggregate. Per micro-batch it runs 288 times a day.",
    action: "B5 — move to the EOD gate." },
  { id: "26", verdict: "bottleneck", name: "G4 Tie-out / Control Totals",
    finding: "Full-table control totals. Same cost class as G2 and the same 288× exposure.",
    action: "B5 — EOD gate only, and it is the gate's strongest check." },
  { id: "27", verdict: "ok", name: "G5 Post-Publish Recon",
    finding: "Already daily and post-publish. Unaffected by the substitution, provided it is not naively moved to per micro-batch for symmetry.",
    action: "Leave alone." },
  { id: "28", verdict: "gap", name: "DQ Framework",
    finding: "No event DQ taxonomy. The failure modes of an envelope and a pull — unknown view, key not found, pull timeout, sequencer cycle — have no codes and therefore no reporting.",
    action: "Extend the taxonomy before the codes are invented ad hoc in three places." },
  { id: "29", verdict: "gap", name: "Error Handling & Quarantine",
    finding: "A file quarantine. The event path has no dead-letter, so a poison envelope has no escape and stalls its partition.",
    action: "M15 — the highest-value single addition in this review." },
  { id: "30", verdict: "gap", name: "Reconciliation Framework",
    finding: "Three boundaries, all downstream of Stage 1. The event path adds four upstream of them: events received → distinct keys → rows pulled → Stage 1 loaded. Without those, event loss is undetectable by construction.",
    action: "Add the four. This is what makes E4 detectable." },
  { id: "31", verdict: "degraded", name: "Audit & Lineage",
    finding: "Because the pull re-reads current state, lineage runs Gold row → micro-batch → key and never Gold row → the specific change that caused it. That is a permanent reduction in what lineage can answer, and it should be stated rather than discovered.",
    action: "State the limit. Add MICROBATCH_ID to carry what remains." },
  { id: "33", verdict: "amend", name: "Metadata & Configuration Store",
    finding: "Needs three new catalogues: the view catalogue, the eventid → domain/view map, and the expectation store.",
    action: "M17 and M18 land here." },
  { id: "34", verdict: "gap", name: "Observability",
    finding: "No consumer lag, no sequence gap detection, no micro-batch state. The primary ingestion path is unobserved, and Splunk volume is about to change order of magnitude.",
    action: "M16, M10, B9." },
  { id: "55", verdict: "bottleneck", name: "Oracle Connection Pooling",
    finding: "Sized for daily fan-out. Intraday multiplies concurrent sessions by the cadence, with a worker pod per mapped task opening its own connections.",
    action: "B7 — bound the pool per pod and the pods per micro-batch." },
  { id: "62", verdict: "gap", name: "HA / DR",
    finding: "No RPO or RTO anywhere in the pack. Under events, Event Hub retention *is* the recovery window and therefore the RTO — and retention is unstated.",
    action: "State retention, then derive RPO and RTO from it rather than the reverse." },
];

export const AR_VERDICTS = {
  broken:     ["#b3261e", "assumption does not survive"],
  bottleneck: ["#a8560f", "works, but not at this rate"],
  rebuild:    ["#6d3ac0", "wrong shape for events"],
  gap:        ["#cc3344", "nothing owns this"],
  risk:       ["#a8560f", "correct and dangerous"],
  degraded:   ["#8a6d1f", "capability permanently reduced"],
  amend:      ["#0b5e83", "small change, free now"],
  demoted:    ["#5c7c94", "still needed, no longer primary"],
  ok:         ["#159943", "unaffected"],
};

export const AR_SEV = {
  critical: "#b3261e",
  high:     "#d97706",
  medium:   "#0b5e83",
};
