// Integration360 — component register for the C4 design route.
// Design readiness, not build progress: a component is "Specified" when there
// is enough information to build it, "Blocked" when an answer is missing.
// Keep in step with the Integration360 design document.

export const I360_SUMMARY = {
 title: "Integration360 — read-only observability over BBH ↔ SEI integration",
 line: "38 components across 6 planes. Observes four channels and answers three questions per business date: completeness, timeliness, correctness. Owns no integration state — the Integration Hub owns quarantine, error handling and remediation.",
};

export const I360_PLANES = {
 UI:    ["Presentation · Web UI",           "▤", "estate board · four channel views · exception list · timeline"],
 RTR:   ["Read API · routers",              "⇄", "one router per channel plus estate, exceptions and reconciliation"],
 ADP:   ["Read API · source adapters",      "⇱", "one adapter per source · no SQL join spans them"],
 SVC:   ["Read API · shared services",      "⚙", "correlation · status normalisation · redaction on read"],
 ENG:   ["Observation Engine · scheduled",  "◷", "verdicts · expectation · cross-channel recon · gap detection"],
 STORE: ["INT360 Store · owned state",      "▣", "five tables · derived state only"],
};

export const I360_STATES = ["Blocked", "Assumed", "Specified", "Not owned"];
export const I360_PCT = { Blocked: 10, Assumed: 45, Specified: 80, "Not owned": 100 };
export const I360_COLOR = { Blocked: "#cc3344", Assumed: "#e0a13d", Specified: "#159943", "Not owned": "#6d3ac0" };

export const I360_COMPONENTS = [
 // ---- Presentation ----
 { id: "UI-1", plane: "UI", component: "EstateBoard", state: "Assumed",
   deliverable: "Four channels by three questions, one business date",
   detail: "Twelve cells, each clicking through to the channel beneath it. Reads rollups and verdict snapshots only, never live source tables.",
   note: "Assumes the morning question is 'did last night work'. No user research exists." },
 { id: "UI-2", plane: "UI", component: "EventChannelView", state: "Assumed",
   deliverable: "Micro-batches, lag per partition, sequence gaps, marker coverage",
   detail: "Shows the pull-complete state that actually gates the business date.",
   note: "Shows that a key changed, never what changed — the envelope carries no data and the pull re-reads current state. Flow health, not lineage." },
 { id: "UI-3", plane: "UI", component: "StandbyFileView", state: "Specified",
   deliverable: "Fallback readiness per interface, plus the trailer count",
   detail: "Three states: absent, arrived-and-held, unavailable. Answers 'is the parachute packed', not 'did the data arrive'.",
   note: "FILE_REGISTRY has no terminal state meaning 'available and deliberately unused'." },
 { id: "UI-4", plane: "UI", component: "OutboundView", state: "Specified",
   deliverable: "Submission lifecycle per loader type, with both status sources on the row",
   detail: "Generated → submitted → notified → terminal, carrying submitted, accepted and rejected counts. Never a boolean: partial acceptance is the norm and Unified Cash and Free Movement carry record-level approval. Each status transition shows whether it arrived by push or by poll.",
   note: "Unblocked: SEI pushes the notification, BBH polls SEI for detail and as backstop. A submission whose terminal state was found only by poll is shown as such — that is the measure of the push channel’s own health." },
 { id: "UI-5", plane: "UI", component: "ExceptionList", state: "Specified",
   deliverable: "One list over three sources with different vocabularies",
   detail: "Row-level business DQ, dbt structural tests, and the Hub's quarantine and transport errors. Sorted by days to expiry first.",
   note: "Read-only. The SEI diagram labels this 'Exception Management'; here it is exception visibility." },
 { id: "UI-7", plane: "UI", component: "LiveFlowBoard", state: "Blocked",
   deliverable: "The intraday clock \u2014 micro-batch by partition, live",
   detail: "Grid of micro-batch against partition, with consumer lag per partition, last batch per topic and current backlog. Localises a stall: 'partition 2 stopped at 04:12' rather than 'the event channel is behind'.",
   note: "Blocked on partition count per domain topic. Without a denominator, 'all partitions reported' cannot be distinguished from 'the ones I happened to see'." },
 { id: "UI-8", plane: "UI", component: "StageFunnel", state: "Specified",
   deliverable: "Six numbers for one date that must tie",
   detail: "Events received \u2192 distinct keys \u2192 rows pulled \u2192 Stage 1 \u2192 INT \u2192 Gold, each with its explained deduction: duplicates collapsed, not-found keys, source-DQ filtered, missing-dimension held.",
   note: "Puts the four event-side boundaries in front of the medallion's existing four, so the chain reads as one funnel rather than two disconnected halves." },
 { id: "UI-6", plane: "UI", component: "BusinessDateTimeline", state: "Specified",
   deliverable: "Date → intraday cycle → micro-batch → transformation task",
   detail: "Resolves to 'the transformation failed at build_dim, attempt 2, at 04:12', then deep-links to the Airflow UI.",
   note: "Deliberately does not reproduce Airflow's task view." },

 // ---- Routers ----
 { id: "API-1", plane: "RTR", component: "estate_router", state: "Specified",
   deliverable: "GET /estate · GET /estate/history",
   detail: "Serves the twelve-cell summary entirely from rollups and verdict snapshots, so the landing page never scans a source table." },
 { id: "API-2", plane: "RTR", component: "event_router", state: "Assumed",
   deliverable: "GET /event/{date} · /microbatch/{id} · /lag",
   detail: "Lag is computed from broker enqueue metadata — the four-field envelope carries no timestamp of its own.",
   note: "Requires the staging store to capture (topic, partition, offset, enqueued_ts, sequence_number) at receipt." },
 { id: "API-3", plane: "RTR", component: "file_router", state: "Specified",
   deliverable: "GET /file/{date} · /interface/{name}",
   detail: "Distinguishes the three states the completeness gate collapses into two: absent, committed-but-not-released, released." },
 { id: "API-4", plane: "RTR", component: "loader_router", state: "Specified",
   deliverable: "GET /loader/{date} · /submission/{id} · /submission/{id}/errors",
   detail: "Submissions joined to their status history, with the template version in force at generation and the source of every transition. Reject detail is served from what the Hub already fetched and stored — Integration360 never calls SEI.",
   note: "Still depends on the Hub recording a submission at send time. Without that record, silence is indistinguishable from success — settling the callback contract did not remove that dependency." },
 { id: "API-5", plane: "RTR", component: "exception_router", state: "Specified",
   deliverable: "GET /exceptions · /{source}/{id}",
   detail: "Filters by grain so row-level and model-level failures appear together without being merged." },
 { id: "API-6", plane: "RTR", component: "recon_router", state: "Assumed",
   deliverable: "GET /recon/{date} · /boundary/{name}",
   detail: "The pipeline's four boundaries, the event channel's four, the outbound six, and the cross-channel check that exists only here.",
   note: "Assumes RECON_RESULT gains MODEL_NAME. Without it, account, client and transaction results collide." },

 // ---- Adapters ----
 { id: "ADP-1", plane: "ADP", component: "oracle_control_reader", state: "Specified",
   deliverable: "Registries, date control, micro-batches, DQ store, recon",
   detail: "The largest adapter. Defends against status values outside the documented state machine — FILE_REGISTRY.STATUS has no check constraint.",
   note: "Needs a dedicated read-only account. Unrequested rather than refused." },
 { id: "ADP-2", plane: "ADP", component: "airflow_reader", state: "Blocked",
   deliverable: "dag_run · task_instance · task_fail",
   detail: "Replica only. The scheduler polls its metadata database continuously and uses SELECT FOR UPDATE; an analytical scan against the primary degrades scheduling.",
   note: "Postgres does not hold task logs — the log table holds audit events. Blocked on whether a replica exists and how the API authenticates." },
 { id: "ADP-3", plane: "ADP", component: "hub_reader", state: "Blocked",
   deliverable: "Quarantine, transport errors, remediation, submissions",
   detail: "Reads what the Integration Hub is holding and what it retried.",
   note: "Blocked on where the Hub's store lives — its own persistence is likely rather than the shared Oracle schema." },
 { id: "ADP-4", plane: "ADP", component: "inbox_reader", state: "Not owned",
   deliverable: "Consumes the shared callback inbox",
   detail: "Tracks its own progress marker, independent of the Hub’s. The inbox holds notifications, not reject payloads — detail is fetched separately on the poll leg. Stored encrypted, masked on read.",
   note: "Dedupe must key on a SEI-supplied message id stable across retries, not a timestamp. BBH defines the contract, so this can be required." },
 { id: "ADP-5", plane: "ADP", component: "dbt_results_reader", state: "Assumed",
   deliverable: "Per-model status, timing, rows affected, test outcomes",
   detail: "Read from a table, not from run_results.json on disk.",
   note: "Requires dbt persisting run results to Oracle via on-run-end. A small pipeline change, free while nothing is deployed." },
 { id: "ADP-6", plane: "ADP", component: "landing_trailer_reader", state: "Blocked",
   deliverable: "Header and trailer of a standby file — two lines",
   detail: "Obtains the declared row count. Never loads the file. It is the left-hand side of the only independent check on the primary ingestion path.",
   note: "Blocked on a landing-zone read mount, or an upstream component publishing the count instead." },

 { id: "ADP-7", plane: "ADP", component: "loader_status_reader", state: "Assumed",
   deliverable: "LOADER_SUBMISSION · LOADER_STATUS_HISTORY · LOADER_ERROR",
   detail: "Reads the outbound state the Hub maintains from both sources. Requires LOADER_STATUS_HISTORY to carry a SOURCE column separating CALLBACK from POLL; without it the two channels cannot be told apart and divergence is unmeasurable.",
   note: "Assumes reject detail is persisted when fetched rather than re-read from SEI on demand. If SEI purges detail after a retention window, a missed fetch is permanent loss and the persisted copy is all that survives." },

 // ---- Shared services ----
 { id: "SVC-1", plane: "SVC", component: "correlation_service", state: "Specified",
   deliverable: "Assembles one answer across five separate databases",
   detail: "No SQL join spans Oracle and the Airflow replica, so any cross-source statement is composed here or precomputed into a rollup.",
   note: "This is why the rollup tables are structural rather than a performance nicety." },
 { id: "SVC-2", plane: "SVC", component: "status_normalizer", state: "Specified",
   deliverable: "native_status alongside normalized_status",
   detail: "Mapping is configuration, never code. An unknown native value populates status_reason and raises an alert; it is never silently mapped. Terminal status never regresses." },
 { id: "SVC-3", plane: "SVC", component: "redactor", state: "Assumed",
   deliverable: "Masks business keys on the way out",
   detail: "Applied on read rather than at rest, so a wrong mask can be corrected without having destroyed the original.",
   note: "786 PII fields are in SDC scope and the masking policy is unapproved. Default to hashing business keys." },

 { id: "SVC-4", plane: "SVC", component: "status_precedence", state: "Specified",
   deliverable: "One current status from two writers, by a written rule",
   detail: "The poll wins. A poll is a read of SEI’s current state; a notification is a point-in-time event that can arrive late or out of order. History keeps every row from both sources; the current status is derived as the latest POLL at or after the newest CALLBACK, otherwise the highest terminal state reached. Terminal never regresses.",
   note: "Without the rule, a retried PROCESSING notification landing after a COMPLETED poll walks the status backwards and raises a false exception. Two writers into one status field and no precedence is how a status board loses its audience." },

 // ---- Observation engine ----
 { id: "ENG-1", plane: "ENG", component: "verdict_computer", state: "Blocked",
   deliverable: "SLA state and reconciliation verdict, per channel per date",
   detail: "Writes each verdict with the threshold that was in force at computation time. The verdict stays derived; storing the input makes it reproducible and stops this system disagreeing with Splunk.",
   note: "Blocked on where the recon tolerance and SLA warning percentage live in configuration. Neither is persisted today." },
 { id: "ENG-2", plane: "ENG", component: "expectation_evaluator", state: "Blocked",
   deliverable: "What was due, against what happened",
   detail: "Without it Integration360 reports presence and absence but never lateness — and lateness is what operations needs.",
   note: "No channel has an expectation model. One table covering feeds, loaders and markers closes all three, because the marker gives events the same shape as files." },
 { id: "ENG-3", plane: "ENG", component: "cross_channel_reconciler", state: "Assumed",
   deliverable: "File trailer count vs events received vs marker count",
   detail: "Three numbers that must agree. A missing file is obvious; a stream that quietly dropped three percent of ACCOUNT events is not, and nothing else in the estate would catch it.",
   note: "Assumes the marker carries a declared count, and that authority between file and event is settled." },
 { id: "ENG-4", plane: "ENG", component: "gap_detector", state: "Specified",
   deliverable: "Sequence gaps · missing markers · stale loads · silent callbacks",
   detail: "Four checks with no owner anywhere else. Event Hub sequence numbers are monotonic per partition, so a gap is a provably lost event — a stronger completeness check than the file channel has." },
 { id: "ENG-7", plane: "ENG", component: "cadence_baseline", state: "Specified",
   deliverable: "Rolling inter-micro-batch interval, per topic",
   detail: "Turns 'MB 1049 has not arrived' into 'MB 1049 is 40 minutes overdue against a 6-minute norm'. Lateness on the event channel comes from the stream's own rhythm \u2014 micro-batch IDs are sequential and arrive at a characteristic interval.",
   note: "Does not cover EOD. There is one marker a day and no rhythm to baseline against, so its expected arrival time still has to be stated." },
 { id: "ENG-5", plane: "ENG", component: "rollup_builder", state: "Specified",
   deliverable: "Daily aggregates per channel",
   detail: "So a ninety-day trend does not scan the registries live, and cross-source correlation is precomputed rather than assembled per page load." },
 { id: "ENG-6", plane: "ENG", component: "alert_evaluator", state: "Blocked",
   deliverable: "Decides what is worth telling a human, once",
   detail: "Covers only findings no other system sees. The Hub alerts on what it manages, Splunk on what the pipeline emits.",
   note: "Blocked: no egress exists. Splunk is out of scope by decision and no email, Teams or ServiceNow path has an owner." },

 { id: "ENG-8", plane: "ENG", component: "divergence_detector", state: "Specified",
   deliverable: "Where push and poll disagree, and where push never spoke",
   detail: "Three findings. A terminal state found by poll that no notification announced. A notification the next poll contradicts. A submission still non-terminal past its max age, which becomes STATUS_UNRESOLVED rather than sitting at SUBMITTED for ever. The first is a direct measurement of SEI’s push channel and costs nothing once SOURCE is recorded.",
   note: "This finding class exists only because there are two sources. It is the outbound counterpart of the event channel’s sequence-gap check — both turn an absence into a provable one." },

 // ---- Store ----
 { id: "ST-1", plane: "STORE", component: "int360_verdict_snapshot", state: "Specified",
   deliverable: "(channel, business_date, verdict_type)",
   detail: "Derived value, threshold in force, inputs, computed timestamp. Makes 'how often did this breach last quarter' answerable." },
 { id: "ST-2", plane: "STORE", component: "int360_rollup_daily", state: "Specified",
   deliverable: "(channel, business_date)",
   detail: "Counts, durations, exception totals, reconciliation differences, plus precomputed cross-source correlations." },
 { id: "ST-3", plane: "STORE", component: "int360_alert_log", state: "Specified",
   deliverable: "(finding_key, fired_ts)",
   detail: "What was dispatched, to whom, acknowledged or not. Exists so the same finding does not alert repeatedly." },
 { id: "ST-4", plane: "STORE", component: "int360_saved_view", state: "Specified",
   deliverable: "(user_id, view_name)",
   detail: "Filters and layout per user. The only table whose loss would inconvenience rather than damage." },
 { id: "ST-5", plane: "STORE", component: "int360_annotation", state: "Assumed",
   deliverable: "(observation_ref, created_ts) — optional",
   detail: "'Known issue, SEI ticket 4471.' Strict observability says no; every operations team eventually asks. Attaches to an observation, never to a pipeline record.",
   note: "The one write path this scope might legitimately grow." },
];

export const I360_CHANNELS = [
 { ch: "Event",  dir: "SEI → BBH", status: "primary ingestion", tone: "#0e8f7e",
   can: "Micro-batch completeness, lag per partition, sequence gaps, marker coverage, pull-complete gating",
   cant: "What changed — the envelope carries no data and the pull re-reads current state" },
 { ch: "File",   dir: "SEI → BBH", status: "daily standby", tone: "#159943",
   can: "Fallback readiness per interface, plus the trailer count for the cross-channel check",
   cant: "Nothing about the data itself — the file is not loaded" },
 { ch: "Loader", dir: "BBH → SEI", status: "push + poll", tone: "#a8560f",
   can: "Submission lifecycle, accepted and rejected counts, reject detail, template version in force, and whether each status arrived by push or by poll",
   cant: "Lateness — nothing records which loaders were due" },
 { ch: "API",    dir: "both",      status: "not Day 1", tone: "#8a97a3",
   can: "Nothing yet — Day 1 is file and event based",
   cant: "Its first production member is the loader callback endpoint itself" },
];

// The outbound loader channel — settled mechanism. Push notifies, poll fetches
// detail and backstops a notification that never arrives. The Integration Hub owns
// all three legs; Integration360 observes them and measures where they disagree.
export const I360_OUTBOUND = [
 { leg: "1 · Submit", dir: "BBH → SEI", owner: "Integration Hub",
   what: "Loader file generated to SEI’s template and submitted through Apigee. Returns the submission identifier every later leg correlates on.",
   obs: "Generated but never submitted, and the template version in force at generation." },
 { leg: "2 · Notify", dir: "SEI → BBH", owner: "Integration Hub · shared inbox",
   what: "SEI calls the BBH endpoint with a status transition and an error summary. Thin and event-shaped. Acknowledged on durable write, never on successful processing — parsing and correlation happen downstream of the 202.",
   obs: "Notification arrival and its latency against submission, plus duplicates collapsed on the SEI-supplied message id." },
 { leg: "3 · Poll", dir: "BBH → SEI", owner: "Integration Hub · monitoring worker",
   what: "Non-terminal submissions only, on a tiered cadence that is tight after submission and backs off. Fetches current state, and reject detail once on reaching a terminal-with-errors state — paginated, stored, never re-fetched per poll.",
   obs: "Submissions past max age, poll results contradicting a notification, and terminal states no notification announced." },
];
