// SEI-BBH Component Design Tracker — generated from SEI-BBH_Component_Design_Tracker.xlsx
// Regenerate by re-running the extraction against an updated workbook.
export const TRACKER_SUMMARY = {
 "title": "SEI - BBH Integration: Engineering Design Tracker",
 "line": "65 components across 4 zones. Python (ingestion) + dbt (transformation) + Airflow (orchestration) on OpenShift/Oracle. One design document per component; Custom Build = High means design doc mandatory before code.",
 "zones": [
  {
   "zone": "1. SEI",
   "components": 7,
   "p1": 3,
   "high": 0
  },
  {
   "zone": "2. Hub",
   "components": 29,
   "p1": 21,
   "high": 12
  },
  {
   "zone": "3. Consumers",
   "components": 7,
   "p1": 1,
   "high": 0
  },
  {
   "zone": "4. OpenShift",
   "components": 22,
   "p1": 11,
   "high": 1
  }
 ],
 "totals": {
  "components": 65,
  "p1": 36,
  "high": 13,
  "new": 28,
  "decisions": 12
 }
};

export const TRACKER_COMPONENTS = [
{
"id": "1",
"zone": "1. SEI",
"plane": "Source",
"component": "SWP Platform",
"deliverable": "Interface spec: domains, entities, extract triggers",
"questions": "Which domains are in scope for phase 1?",
"depends": "-",
"source": "SEI v5",
"priority": "P1",
"technology": "Contract",
"custom": "None",
"scope": "SEI-owned. Specification review only.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "2",
"zone": "1. SEI",
"plane": "Source",
"component": "SWP UI",
"deliverable": "Access model + SSO handshake spec",
"questions": "Which BBH roles need UI access?",
"depends": "36",
"source": "SEI v5",
"priority": "P3",
"technology": "Contract",
"custom": "None",
"scope": "SEI-owned.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "3",
"zone": "1. SEI",
"plane": "Source",
"component": "SWP APIs",
"deliverable": "API contract: endpoints, auth, rate limits, SLAs",
"questions": "Which consumers use real-time vs batch?",
"depends": "12",
"source": "SEI v5",
"priority": "P1",
"technology": "Contract",
"custom": "None",
"scope": "SEI-owned. Consume as published.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "4",
"zone": "1. SEI",
"plane": "Source",
"component": "SWP Loaders",
"deliverable": "Loader file format + submission/ack contract",
"questions": "Sync or async ack? Failure semantics?",
"depends": "10, 11",
"source": "SEI v5",
"priority": "P2",
"technology": "Contract",
"custom": "None",
"scope": "SEI-owned.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "5",
"zone": "1. SEI",
"plane": "Source",
"component": "Extract Generation",
"deliverable": "File spec: layout, naming, manifest, EOD + intraday cadence",
"questions": "Full snapshot daily, or change-indicator available?",
"depends": "8",
"source": "SEI v5",
"priority": "P1",
"technology": "Contract",
"custom": "None",
"scope": "SEI-owned. Ask for hash/change column - biggest volume lever.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "6",
"zone": "1. SEI",
"plane": "PS-Orchestration",
"component": "Orchestration API / Data Ingestion / ODM / Workflows / Config",
"deliverable": "Outbound orchestration design (SEI-owned, BBH-reviewed)",
"questions": "Is outbound in scope this phase?",
"depends": "10, 11",
"source": "SEI v5",
"priority": "P3",
"technology": "Contract",
"custom": "None",
"scope": "SEI-owned.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "7",
"zone": "1. SEI",
"plane": "PS-Orchestration",
"component": "Status Monitoring Dashboard",
"deliverable": "Status event contract to Integration360",
"questions": "Does this or Integration360 hold the recon record?",
"depends": "35",
"source": "SEI v5",
"priority": "P2",
"technology": "Contract",
"custom": "Low",
"scope": "Event schema agreement; no BBH build.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "8",
"zone": "2. Hub",
"plane": "Ingress/Egress",
"component": "Landing Zone + Transport",
"deliverable": "Transport design: protocol, auth, dirs, retention, completeness signal",
"questions": "sFTP or object store? Same for EOD and intraday?",
"depends": "5",
"source": "Both (conflict)",
"priority": "P1",
"technology": "Infra",
"custom": "Low",
"scope": "Managed service + config. Custom only for manifest/completeness check.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "9",
"zone": "2. Hub",
"plane": "Ingress/Egress",
"component": "File Arrival Sensors",
"deliverable": "Per-file sensor design; start-on-arrival not batch-complete",
"questions": "Manifest-driven or filename pattern?",
"depends": "8, 18",
"source": "NEW",
"priority": "P1",
"technology": "Airflow",
"custom": "Medium",
"scope": "Custom sensor/deferrable operator per domain. Base sensors do not know your manifest.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "10",
"zone": "2. Hub",
"plane": "Ingress/Egress",
"component": "Outbound Producers",
"deliverable": "Design for Data Extracts, JSON payloads, Loader File",
"questions": "Which BBH systems are sources?",
"depends": "43",
"source": "SEI v5",
"priority": "P3",
"technology": "Python",
"custom": "High",
"scope": "Full custom build: extract, JSON serialisation, loader-file format per SEI spec.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "11",
"zone": "2. Hub",
"plane": "Ingress/Egress",
"component": "Apigee Proxy",
"deliverable": "Proxy design: submit path + status-return path",
"questions": "Is Apigee a decision or a placeholder? (AD-3)",
"depends": "10, 35",
"source": "SEI v5",
"priority": "P3",
"technology": "Vendor/Infra",
"custom": "Low",
"scope": "Proxy config + policies. No application code.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "12",
"zone": "2. Hub",
"plane": "Ingress/Egress",
"component": "API Gateway / Data Plane",
"deliverable": "Real-time route design, independent of batch",
"questions": "Does intraday run here or on batch? (AD-4)",
"depends": "3, 42",
"source": "BBH V4.2",
"priority": "P2",
"technology": "Vendor/Infra",
"custom": "Low",
"scope": "Gateway config, routing, throttling policies.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "13",
"zone": "2. Hub",
"plane": "Processing",
"component": "Python Ingestion Framework",
"deliverable": "Module design: validation, profiling, metadata capture, RAW load",
"questions": "cx_Oracle vs SQL*Loader vs External Tables?",
"depends": "8, 14, 23",
"source": "SEI v5",
"priority": "P1",
"technology": "Python",
"custom": "High",
"scope": "CORE BUILD. Reusable config-driven framework, not 7 scripts. Loader abstraction + audit column injection.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "14",
"zone": "2. Hub",
"plane": "Processing",
"component": "Stage 1 RAW",
"deliverable": "Physical model: 7 RAW_* tables, 8 audit cols, partitioning, retention",
"questions": "Partition by BUSINESS_DATE? Purge policy?",
"depends": "13",
"source": "SEI v5",
"priority": "P1",
"technology": "Oracle DDL",
"custom": "None",
"scope": "DDL + partitioning. No application code.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "15",
"zone": "2. Hub",
"plane": "Processing",
"component": "Stage 2 Enriched (dbt)",
"deliverable": "5 STG2_* models, 8 processing steps, tests",
"questions": "Full refresh or incremental per model?",
"depends": "14, 17, 25",
"source": "SEI v5",
"priority": "P1",
"technology": "dbt",
"custom": "Medium",
"scope": "Standard dbt models. Custom macros for dedup and latest-record selection.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "16",
"zone": "2. Hub",
"plane": "Processing",
"component": "Gold (dbt)",
"deliverable": "2 SCD2 dims + 3 facts; SCD2 and merge logic",
"questions": "Writes to Hub schema or PBDW/IMDS direct? (AD-1)",
"depends": "15, 26, 60",
"source": "SEI v5 only",
"priority": "P1",
"technology": "dbt",
"custom": "High",
"scope": "dbt snapshot will NOT cover this. Custom incremental SCD2 macro + merge strategy per fact.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "17",
"zone": "2. Hub",
"plane": "Processing",
"component": "Correction Handling",
"deliverable": "Bitemporal vs merge design, applied across Stage 2 and Gold",
"questions": "One answer both layers. (AD-2)",
"depends": "15, 16, 21",
"source": "Both (conflict)",
"priority": "P1",
"technology": "dbt",
"custom": "High",
"scope": "No dbt idiom for bitemporal. Custom incremental strategy / macro, written once and reused.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "18",
"zone": "2. Hub",
"plane": "Orchestration",
"component": "Airflow DAG + Per-Domain Fan-out",
"deliverable": "DAG design: 7 parallel branches, join points, retries",
"questions": "Where do branches legitimately join?",
"depends": "9, 51, 52",
"source": "SEI v5 + NEW",
"priority": "P1",
"technology": "Airflow",
"custom": "High",
"scope": "Dynamic task mapping over domain config. Not a hand-written static DAG.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "19",
"zone": "2. Hub",
"plane": "Orchestration",
"component": "Dim-before-Fact / dbt Threads",
"deliverable": "Build-order and concurrency design",
"questions": "Thread count vs Oracle contention ceiling?",
"depends": "16, 55",
"source": "NEW",
"priority": "P2",
"technology": "Airflow + dbt",
"custom": "Low",
"scope": "Selector config and thread tuning.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "20",
"zone": "2. Hub",
"plane": "Orchestration",
"component": "Intraday Cadence Control",
"deliverable": "Cadence design and lane assignment",
"questions": "Frequency? Batch pipeline or API route? (AD-4)",
"depends": "12, 18",
"source": "SEI v5",
"priority": "P1",
"technology": "Airflow",
"custom": "Medium",
"scope": "Custom scheduling logic; overlap prevention with the EOD run.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "21",
"zone": "2. Hub",
"plane": "Orchestration",
"component": "Replay / Rerun Engine",
"deliverable": "Replay design from LOAD_ID; scope, idempotency, downstream impact",
"questions": "Replay rewrites Gold in place or appends? (ties to AD-2)",
"depends": "14, 17, 27",
"source": "NEW",
"priority": "P1",
"technology": "Python + Airflow",
"custom": "High",
"scope": "CORE BUILD. Airflow clear/backfill does NOT undo a Gold merge. Bespoke replay orchestration + idempotency.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "22",
"zone": "2. Hub",
"plane": "Orchestration",
"component": "Partial-Batch Policy",
"deliverable": "Policy + implementation: halt-all vs per-domain proceed",
"questions": "Can consumers tolerate a partial business date? (AD-5)",
"depends": "18, 23",
"source": "NEW",
"priority": "P1",
"technology": "Airflow",
"custom": "Medium",
"scope": "Custom branching + trigger rules. Publish-completeness marker per domain.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "23",
"zone": "2. Hub",
"plane": "Data Quality",
"component": "G1 File / Structural Gate",
"deliverable": "Check set + quarantine design. BLOCKS RAW insert",
"questions": "Which failures are fatal vs warn?",
"depends": "8, 13, 28",
"source": "SEI v5",
"priority": "P1",
"technology": "Python",
"custom": "High",
"scope": "Custom validation engine driven by the rule registry. Blocking semantics + quarantine.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "24",
"zone": "2. Hub",
"plane": "Data Quality",
"component": "G2 RAW Profiling Gate",
"deliverable": "Profiling checks. BLOCKS Stage 2",
"questions": "Thresholds absolute or vs trailing average?",
"depends": "14, 28",
"source": "SEI v5",
"priority": "P2",
"technology": "Airflow + SQL",
"custom": "Medium",
"scope": "Aggregate SQL pushed to Oracle; custom threshold comparison and branch.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "25",
"zone": "2. Hub",
"plane": "Data Quality",
"component": "G3 dbt Tests + Business Rules",
"deliverable": "Test suite + rule design. BLOCKS Gold",
"questions": "Which rules are dbt tests vs model logic?",
"depends": "15, 28",
"source": "SEI v5",
"priority": "P1",
"technology": "dbt",
"custom": "Medium",
"scope": "Generic tests cover basics; custom singular tests + generic test macros for business rules.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "26",
"zone": "2. Hub",
"plane": "Data Quality",
"component": "G4 Tie-out / Control Totals",
"deliverable": "RAW-to-Gold reconciliation. BLOCKS Gold publish. Per-target",
"questions": "Recount or compare to captured ingest metadata?",
"depends": "14, 16, 28",
"source": "NEW",
"priority": "P1",
"technology": "Airflow + SQL",
"custom": "High",
"scope": "CORE BUILD. dbt tests cannot do this - it crosses the graph and must gate the publish.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "27",
"zone": "2. Hub",
"plane": "Data Quality",
"component": "G5 Post-Publish Recon",
"deliverable": "Advisory recon; triggers replay",
"questions": "What auto-triggers a replay vs pages a human?",
"depends": "16, 21",
"source": "SEI v5",
"priority": "P2",
"technology": "Airflow + SQL",
"custom": "Medium",
"scope": "Custom recon queries + replay trigger integration.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "28",
"zone": "2. Hub",
"plane": "Data Quality",
"component": "DQ Framework",
"deliverable": "Rule registry, severity tiers, results store, audited override path",
"questions": "Who can override at 2am, and how is it logged?",
"depends": "33, 31",
"source": "NEW",
"priority": "P1",
"technology": "Python",
"custom": "High",
"scope": "CORE BUILD. Registry schema, severity model, results store, override API + audit trail.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "29",
"zone": "2. Hub",
"plane": "Foundation",
"component": "Error Handling & Quarantine",
"deliverable": "Error taxonomy, quarantine store, resubmission path",
"questions": "Quarantine retention and reprocessing route?",
"depends": "23, 50",
"source": "Both",
"priority": "P1",
"technology": "Python",
"custom": "High",
"scope": "Custom taxonomy + quarantine lifecycle + resubmission path.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "30",
"zone": "2. Hub",
"plane": "Foundation",
"component": "Reconciliation Framework",
"deliverable": "Recon model: control totals, exception lifecycle",
"questions": "Who owns the recon record? (AD-6)",
"depends": "26, 27, 35",
"source": "Both",
"priority": "P1",
"technology": "Python",
"custom": "High",
"scope": "Custom recon data model + exception lifecycle + Integration360 publication.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "31",
"zone": "2. Hub",
"plane": "Foundation",
"component": "Audit & Lineage",
"deliverable": "End-to-end lineage design, evidence retention",
"questions": "Is lineage audit-defensible under AD-2?",
"depends": "14, 17",
"source": "Both",
"priority": "P1",
"technology": "Python + dbt",
"custom": "Medium",
"scope": "dbt docs covers model lineage only. Custom row-level lineage via LOAD_ID chain.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "32",
"zone": "2. Hub",
"plane": "Foundation",
"component": "Security & Access Control",
"deliverable": "AuthN/AuthZ model, data classification, masking",
"questions": "Any PII in SWP extracts requiring masking?",
"depends": "47, 48",
"source": "BBH V4.2",
"priority": "P1",
"technology": "Infra",
"custom": "Low",
"scope": "Oracle roles/grants + platform controls. Custom only if masking required.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "33",
"zone": "2. Hub",
"plane": "Foundation",
"component": "Metadata & Configuration Store",
"deliverable": "Config model: rules, thresholds, mappings, schedules",
"questions": "One store, or does SEI keep its own? (risk R1)",
"depends": "6, 28",
"source": "Both",
"priority": "P1",
"technology": "Oracle DDL + Python",
"custom": "High",
"scope": "CORE BUILD. Everything config-driven depends on this. Build first.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "34",
"zone": "2. Hub",
"plane": "Foundation",
"component": "Observability",
"deliverable": "Logs, metrics, traces; SLIs and alerting",
"questions": "What are the SLOs for the EOD window?",
"depends": "64",
"source": "BBH V4.2",
"priority": "P2",
"technology": "Infra",
"custom": "Low",
"scope": "Standard stack + custom metric emission from Python/Airflow.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "35",
"zone": "2. Hub",
"plane": "Foundation",
"component": "Integration360",
"deliverable": "Monitoring, exception mgmt, process tracking, recon",
"questions": "Does it become the system of record? (AD-6)",
"depends": "7, 30",
"source": "Both",
"priority": "P1",
"technology": "Vendor/BBH",
"custom": "Medium",
"scope": "Existing BBH platform. Custom feed/adapter from the Hub.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "36",
"zone": "2. Hub",
"plane": "Foundation",
"component": "SSO",
"deliverable": "SSO design to SWP UI",
"questions": "Federation protocol and identity source?",
"depends": "2",
"source": "SEI v5",
"priority": "P3",
"technology": "Infra",
"custom": "None",
"scope": "Configuration only.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "37",
"zone": "3. Consumers",
"plane": "Consumers",
"component": "PBDW",
"deliverable": "Publication design + change control",
"questions": "Direct dbt writes or publish pattern? (AD-1)",
"depends": "16, 60",
"source": "Both",
"priority": "P1",
"technology": "Oracle DDL + dbt",
"custom": "Medium",
"scope": "Existing tables. Custom publish/swap pattern if AD-1 lands Hub-owned.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "38",
"zone": "3. Consumers",
"plane": "Consumers",
"component": "IMDS Stage -> IMDS",
"deliverable": "Staging DB + load design from Stage 2",
"questions": "Missing from BBH deck - confirm it exists",
"depends": "15",
"source": "SEI v5 only",
"priority": "P2",
"technology": "Oracle DDL + dbt",
"custom": "Medium",
"scope": "New staging schema + load models.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "39",
"zone": "3. Consumers",
"plane": "Consumers",
"component": "Pivotal Database",
"deliverable": "Feed design from Stage 2",
"questions": "Absent from SEI 8-component list - scope gap",
"depends": "15",
"source": "BBH V4.2 only",
"priority": "P2",
"technology": "dbt",
"custom": "Medium",
"scope": "New feed. Not costed in SEI scope.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "40",
"zone": "3. Consumers",
"plane": "Consumers",
"component": "CP DW Canonical Model",
"deliverable": "Forward-compatibility design only (future)",
"questions": "Keep Stage 2 neutral enough to attach later",
"depends": "15",
"source": "BBH V4.2 (future)",
"priority": "P3",
"technology": "Design only",
"custom": "None",
"scope": "No build this phase. Design constraint on Stage 2 only.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "41",
"zone": "3. Consumers",
"plane": "Consumers",
"component": "BI / Analytics",
"deliverable": "Semantic layer + access design",
"questions": "Which of ~1000 consumers land where?",
"depends": "16",
"source": "SEI v5",
"priority": "P2",
"technology": "BI tooling",
"custom": "Low",
"scope": "Power BI / Tableau models. Outside the Python/dbt stack.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "42",
"zone": "3. Consumers",
"plane": "Consumers",
"component": "Real-time Consumers",
"deliverable": "Consumer contract on the API lane",
"questions": "Which use cases justify real-time?",
"depends": "12",
"source": "BBH V4.2",
"priority": "P2",
"technology": "Contract",
"custom": "None",
"scope": "Consumer-side build, not Hub.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "43",
"zone": "3. Consumers",
"plane": "Consumers",
"component": "BBH Existing Systems",
"deliverable": "Impact assessment: front/back office, trade, custody",
"questions": "Which are sources for outbound?",
"depends": "10",
"source": "SEI v5",
"priority": "P3",
"technology": "Analysis",
"custom": "None",
"scope": "Assessment only this phase.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "44",
"zone": "4. OpenShift",
"plane": "Platform",
"component": "Projects / Namespaces",
"deliverable": "Environment topology: dev, test, UAT, prod",
"questions": "Namespace per env, or per env per component?",
"depends": "-",
"source": "NEW",
"priority": "P1",
"technology": "Infra",
"custom": "None",
"scope": "Platform config.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "45",
"zone": "4. OpenShift",
"plane": "Platform",
"component": "Container Images",
"deliverable": "Base image standard: Python, dbt, Airflow",
"questions": "Who owns base image patching cadence?",
"depends": "57",
"source": "NEW",
"priority": "P1",
"technology": "Infra",
"custom": "Medium",
"scope": "Custom Dockerfiles per runtime; dependency pinning for dbt + cx_Oracle.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "46",
"zone": "4. OpenShift",
"plane": "Platform",
"component": "Registry, Scanning, Signing",
"deliverable": "Image supply-chain design + promotion policy",
"questions": "What CVE severity blocks promotion?",
"depends": "45, 57",
"source": "NEW",
"priority": "P2",
"technology": "Infra",
"custom": "None",
"scope": "Tooling config.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "47",
"zone": "4. OpenShift",
"plane": "Platform",
"component": "Service Accounts, RBAC, SCCs",
"deliverable": "Cluster access model",
"questions": "Least-privilege per workload?",
"depends": "32",
"source": "NEW",
"priority": "P1",
"technology": "Infra",
"custom": "None",
"scope": "Platform config.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "48",
"zone": "4. OpenShift",
"plane": "Platform",
"component": "Secrets Management",
"deliverable": "Secrets design: Oracle creds, sFTP keys, API tokens",
"questions": "Vault or sealed secrets? Rotation policy?",
"depends": "32",
"source": "NEW",
"priority": "P1",
"technology": "Infra",
"custom": "Low",
"scope": "Config + custom secret injection into Airflow connections.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "49",
"zone": "4. OpenShift",
"plane": "Platform",
"component": "Network Policy & Egress",
"deliverable": "Egress to SEI/Apigee/Oracle; ingress rules",
"questions": "Firewall path to SEI approved?",
"depends": "8, 11",
"source": "NEW",
"priority": "P1",
"technology": "Infra",
"custom": "None",
"scope": "Network config. Long lead time - start early.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "50",
"zone": "4. OpenShift",
"plane": "Platform",
"component": "Persistent Storage",
"deliverable": "Volume design: landing, quarantine, dbt artifacts, logs",
"questions": "Capacity for retention window?",
"depends": "8, 29",
"source": "NEW",
"priority": "P2",
"technology": "Infra",
"custom": "None",
"scope": "Storage class + PVC config.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "51",
"zone": "4. OpenShift",
"plane": "Runtime",
"component": "Airflow Deployment",
"deliverable": "Scheduler HA, KubernetesExecutor, pod operator design",
"questions": "HA scheduler required for the window?",
"depends": "18",
"source": "NEW",
"priority": "P1",
"technology": "Infra + Airflow",
"custom": "Medium",
"scope": "Helm values + custom pod templates per task type.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "52",
"zone": "4. OpenShift",
"plane": "Runtime",
"component": "Worker Pod Autoscaling",
"deliverable": "Autoscaling design sized to the fan-out",
"questions": "Max concurrency before Oracle contention?",
"depends": "18, 55",
"source": "NEW",
"priority": "P1",
"technology": "Infra",
"custom": "Low",
"scope": "HPA/KEDA config. Requires the measurement from item 55.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "53",
"zone": "4. OpenShift",
"plane": "Runtime",
"component": "Resource Quotas & Priority",
"deliverable": "Requests/limits, quotas, priority classes for EOD",
"questions": "Does batch preempt other workloads?",
"depends": "52",
"source": "NEW",
"priority": "P2",
"technology": "Infra",
"custom": "None",
"scope": "Platform config.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "54",
"zone": "4. OpenShift",
"plane": "Runtime",
"component": "Warm-start / Pre-pulled Images",
"deliverable": "Cold-start mitigation design",
"questions": "Cold start cost vs the 5-min window?",
"depends": "45, 52",
"source": "NEW",
"priority": "P2",
"technology": "Infra",
"custom": "Low",
"scope": "Image pre-pull / slim images. Measure first.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "55",
"zone": "4. OpenShift",
"plane": "Runtime",
"component": "Oracle Connection Pooling",
"deliverable": "Pooling design; the real parallelism ceiling",
"questions": "Max sessions DBA will grant?",
"depends": "13, 52",
"source": "NEW",
"priority": "P1",
"technology": "Python + Infra",
"custom": "Medium",
"scope": "Custom pool management in the ingestion framework. Sets the fan-out ceiling.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "56",
"zone": "4. OpenShift",
"plane": "Runtime",
"component": "Node Placement",
"deliverable": "Taints/affinity: batch burst vs always-on API",
"questions": "Dedicated nodes for the real-time lane?",
"depends": "12, 52",
"source": "NEW",
"priority": "P2",
"technology": "Infra",
"custom": "None",
"scope": "Scheduling config.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "57",
"zone": "4. OpenShift",
"plane": "Deployment",
"component": "CI/CD Pipelines",
"deliverable": "Build, test, scan, promote pipeline design",
"questions": "Pipeline per component or monorepo?",
"depends": "45, 46",
"source": "NEW",
"priority": "P1",
"technology": "CI/CD",
"custom": "Medium",
"scope": "Custom pipelines: Python unit tests, dbt compile/test in CI against a test schema.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "58",
"zone": "4. OpenShift",
"plane": "Deployment",
"component": "GitOps / ArgoCD",
"deliverable": "Manifest promotion and drift control",
"questions": "Environment promotion gates?",
"depends": "44, 57",
"source": "NEW",
"priority": "P2",
"technology": "CI/CD",
"custom": "Low",
"scope": "Standard GitOps config.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "59",
"zone": "4. OpenShift",
"plane": "Deployment",
"component": "dbt Release & Rollback",
"deliverable": "dbt versioning, release cadence, rollback design",
"questions": "Rollback of an SCD2 dim - how?",
"depends": "15, 16, 21",
"source": "NEW",
"priority": "P1",
"technology": "dbt + CI/CD",
"custom": "High",
"scope": "No native rollback for a merged SCD2 dim. Custom restore path tied to the replay engine.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "60",
"zone": "4. OpenShift",
"plane": "Deployment",
"component": "Database Change Management",
"deliverable": "DDL control for RAW/STG2/Gold + PBDW/IMDS",
"questions": "Does Gold sit inside BBH prod change control? (AD-1)",
"depends": "16, 37",
"source": "NEW",
"priority": "P1",
"technology": "Process + DDL",
"custom": "Low",
"scope": "Process design + migration tooling.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "61",
"zone": "4. OpenShift",
"plane": "Deployment",
"component": "Blue-Green / Canary (API lane)",
"deliverable": "Zero-downtime release design for real-time",
"questions": "Needed for phase 1 or later?",
"depends": "12",
"source": "NEW",
"priority": "P3",
"technology": "Infra",
"custom": "None",
"scope": "Platform capability.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "62",
"zone": "4. OpenShift",
"plane": "Operations",
"component": "HA / DR",
"deliverable": "DR topology, RTO/RPO for the batch window",
"questions": "What is the agreed RTO/RPO?",
"depends": "44",
"source": "NEW",
"priority": "P2",
"technology": "Infra",
"custom": "Low",
"scope": "Topology design + runbook.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "63",
"zone": "4. OpenShift",
"plane": "Operations",
"component": "Backup & Restore",
"deliverable": "Airflow metadata DB, config store, quarantine volumes",
"questions": "Restore tested how often?",
"depends": "33, 50",
"source": "NEW",
"priority": "P2",
"technology": "Infra",
"custom": "None",
"scope": "Backup tooling config.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "64",
"zone": "4. OpenShift",
"plane": "Operations",
"component": "Monitoring Stack",
"deliverable": "Prometheus/Grafana/log aggregation wired into item 34",
"questions": "One stack, not a parallel one - confirm",
"depends": "34",
"source": "NEW",
"priority": "P2",
"technology": "Infra",
"custom": "Low",
"scope": "Dashboards + alert rules.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
},
{
"id": "65",
"zone": "4. OpenShift",
"plane": "Operations",
"component": "Cost & Capacity Monitoring",
"deliverable": "Capacity model for a sharply peaked EOD burst",
"questions": "Peak-to-average ratio acceptable?",
"depends": "52, 53",
"source": "NEW",
"priority": "P3",
"technology": "Infra",
"custom": "None",
"scope": "Tooling config.",
"owner": "",
"status": "Not Started",
"target": "",
"notes": ""
}
];

export const TRACKER_DECISIONS = [
{
"id": "AD-1",
"decision": "Gold write target: Hub-owned schema vs PBDW/IMDS direct",
"sei": "Gold materialised into existing Oracle DW tables",
"bbh": "No Gold layer; Stage 2 feeds consumers",
"consequence": "dbt writes production schemas; blast radius and change control shift",
"blocks": "16, 37, 60",
"recommendation": "Hub-owned Gold schema that publishes"
},
{
"id": "AD-2",
"decision": "Corrections: in-place merge vs bitemporal append",
"sei": "Merge (update existing) on facts",
"bbh": "Bitemporal handling held in Stage 2",
"consequence": "Merge destroys history; breaks as-of restatement and replay",
"blocks": "17, 21, 31, 59",
"recommendation": "Bitemporal append with as-of resolution"
},
{
"id": "AD-3",
"decision": "Apigee: firm decision or placeholder",
"sei": "BBH runs an Apigee proxy (two nodes)",
"bbh": "Vendor-neutral 'API Gateway / Data Plane'",
"consequence": "SEI presumes a BBH decision",
"blocks": "11, 12",
"recommendation": "Pin explicitly or correct SEI diagram"
},
{
"id": "AD-4",
"decision": "Intraday: batch pipeline or real-time lane",
"sei": "In scope, identical flow to EOD",
"bbh": "Batch lane annotated EOD only",
"consequence": "Window sizing and cadence undefined",
"blocks": "12, 20",
"recommendation": "Decide one lane; not both"
},
{
"id": "AD-5",
"decision": "Partial batch: halt-all vs per-domain proceed",
"sei": "Not addressed",
"bbh": "Not addressed",
"consequence": "Undefined behaviour on single-file failure",
"blocks": "18, 22",
"recommendation": "Halt-all until measured, then relax"
},
{
"id": "AD-6",
"decision": "Monitoring system of record",
"sei": "SEI Status Dashboard AND Integration360",
"bbh": "Integration360 as cross-cutting capability",
"consequence": "Two dashboards, no single truth",
"blocks": "7, 30, 35",
"recommendation": "Integration360 as recon system of record"
},
{
"id": "AD-7",
"decision": "Stage 1 ingestion technology",
"sei": "Python (cx_Oracle / SQL*Loader / External Tables)",
"bbh": "Arrow labelled dbt",
"consequence": "BBH slide is wrong; fix before it is quoted",
"blocks": "13",
"recommendation": "DECIDED: Python. Correct BBH slide"
},
{
"id": "AD-8",
"decision": "RAW immutability",
"sei": "Immutable, append only",
"bbh": "Source as delivered",
"consequence": "-",
"blocks": "14, 21",
"recommendation": "DECIDED: immutable append-only"
},
{
"id": "AD-9",
"decision": "DQ gates blocking vs advisory",
"sei": "DQ check drawn after Gold",
"bbh": "Recon & error handling, unspecified",
"consequence": "Post-Gold check blocks nothing; bad data already published",
"blocks": "23-28",
"recommendation": "DECIDED: blocking, with G4 before publish"
},
{
"id": "AD-10",
"decision": "Transport protocol",
"sei": "Unspecified",
"bbh": "sFTP reception at Landing Zone",
"consequence": "BBH has committed further than SEI",
"blocks": "8, 49",
"recommendation": "Confirm sFTP or agree alternative"
},
{
"id": "AD-11",
"decision": "Outbound scope this phase",
"sei": "Fully diagrammed",
"bbh": "Absent entirely",
"consequence": "Build expectation mismatch",
"blocks": "6, 10, 11",
"recommendation": "State in or explicitly out of scope"
},
{
"id": "AD-12",
"decision": "Pivotal in scope",
"sei": "Not in the 8-component inbound list",
"bbh": "Named consumer of Stage 2",
"consequence": "Scope gap on the SEI side",
"blocks": "39",
"recommendation": "Add to SEI scope or drop"
}
];
