// GENERATED by tools/ingest_sei_docs.py — do not edit by hand.
// Empty until the SEI PDFs are ingested:
//   mkdir -p sei-source && cp /path/to/*.pdf sei-source/
//   python3 tools/ingest_sei_docs.py
// The citation map in seiCitations.js works without this file; ingesting only
// adds the source text beside each citation.

export const SEI_DOCS = [];
