// GENERATED by tools/ingest_sei_docs.py — do not edit by hand.
// Empty until the SEI PDFs are ingested:
//   mkdir -p sei-source && cp /path/to/*.pdf sei-source/
//   python3 tools/ingest_sei_docs.py --publish
// The citation map in seiCitations.js works without this file; ingesting only
// adds the source text beside each citation, and --publish lets the popup link
// straight to a page of the PDF.

export const SEI_DOCS = [];
