# (table, domain, business_name, description, grain, confidence)
# confidence: high = the name and the domain are unambiguous
#             med  = the domain is clear, a term inside the name is inferred
#             low  = an abbreviation nobody outside the team can expand;
#                    these are the review queue, and the UI says so
C = [
# ---- Clients & Accounts -------------------------------------------------
("DIM_ACCOUNT","Clients & Accounts","Account","The accounts BBH holds and services, with how each one is set up and who owns it.","one row per account","high"),
("DIM_ACCOUNT_MAP","Clients & Accounts","Account Cross-Reference","How an account is identified in each system that knows about it, so the same account can be recognised across platforms.","one row per account per external identifier","high"),
("DIM_ACCOUNT_UD","Clients & Accounts","Account User-Defined Fields","Extra account attributes the business added itself, outside the standard account record.","one row per account per user-defined field","high"),
("DIM_ACCOUNT_UD_HIST","Clients & Accounts","Account User-Defined Fields — History","Previous values of those extra account attributes, so a change can be traced to a date.","one row per account per field per change","high"),
("DIM_ACCOUNT_FEE_BLOCKS","Clients & Accounts","Account Fee Blocks","Accounts whose fee billing is currently held, and from when.","one row per account per fee block","high"),
("DIM_ACCOUNT_IR_BLOCKS","Clients & Accounts","Account IR Blocks","Accounts with a hold placed on IR processing. IR is not expanded anywhere in the lineage — confirm before publishing this description.","one row per account per block","low"),
("DIM_MASTER_ACCOUNT_UD","Clients & Accounts","Master Account User-Defined Fields","Extra attributes on a master account — the grouping several accounts are administered under.","one row per master account per field","high"),
("DIM_MASTER_ACCOUNT_UD_HIST","Clients & Accounts","Master Account User-Defined Fields — History","Previous values of those master-account attributes.","one row per master account per field per change","high"),
("DIM_MASTER_ACCOUNT_BLOCKS","Clients & Accounts","Master Account Blocks","Holds placed at master-account level, which apply to every account beneath.","one row per master account per block","high"),
("DIM_MSTR_ACCT_RELATIONSHIP","Clients & Accounts","Master Account Relationships","Which accounts belong to which master account, and in what capacity.","one row per master account to account link","high"),
("DIM_MSTR_ACCT_REL_HIST","Clients & Accounts","Master Account Relationships — History","Previous master-account groupings, so a reorganisation can be traced.","one row per link per change","high"),
("REF_ACCOUNT_OMNI_MAP","Clients & Accounts","Omnibus Account Map","Which underlying accounts sit behind an omnibus account held in a single name.","one row per omnibus account to underlying account link","med"),
("REF_ADDEPAR_ACCOUNT_DTLS","Clients & Accounts","Addepar Account Details","Account details as Addepar holds them, for reporting that runs out of Addepar rather than PBDW.","one row per account in Addepar","high"),
("DIM_COMPANY","Clients & Accounts","Company","The legal entities BBH deals with, whether as client, counterparty or issuer.","one row per company","high"),

# ---- People & Relationships --------------------------------------------
("DIM_INTERESTED_PARTY","People & Relationships","Interested Party","Every person or organisation with an interest in an account — owners, beneficiaries, signatories, advisers.","one row per interested party","high"),
("DIM_INTERESTED_PARTY_UD","People & Relationships","Interested Party User-Defined Fields","Extra attributes the business records against a party.","one row per party per field","high"),
("DIM_INTERESTED_PARTY_UD_HIST","People & Relationships","Interested Party User-Defined Fields — History","Previous values of those party attributes.","one row per party per field per change","high"),
("DIM_IP_RELATIONSHIP","People & Relationships","Party Relationship","How each party relates to each account — the capacity in which they are interested.","one row per party to account relationship","high"),
("DIM_IP_RELATIONSHIP_HIST","People & Relationships","Party Relationship — History","Previous relationships, so a change of signatory or beneficiary can be traced.","one row per relationship per change","high"),
("DIM_IP_RELATIONSHIP_UD","People & Relationships","Party Relationship User-Defined Fields","Extra attributes on the relationship itself rather than on the party.","one row per relationship per field","high"),
("DIM_IP_RELATIONSHIP_UD_HIST","People & Relationships","Party Relationship User-Defined Fields — History","Previous values of those relationship attributes.","one row per relationship per field per change","high"),
("DIM_IP_REL_REMIT_BLOCKS","People & Relationships","Remittance Blocks","Party relationships whose payments are currently blocked, and why.","one row per relationship per remittance block","high"),
("DIM_IP_REL_STMT_BLOCKS","People & Relationships","Statement Blocks","Party relationships whose statements are currently withheld.","one row per relationship per statement block","high"),
("REF_IP_MAIL_LABEL_TITLE","People & Relationships","Mailing Title","The salutation and title used when addressing a party on post.","one row per title code","high"),
("DIM_CONTACT","People & Relationships","Contact","Named contacts and how to reach them.","one row per contact","high"),
("DIM_EMPLOYEE","People & Relationships","Employee","BBH staff, used to attribute accounts and activity to the people responsible.","one row per employee","high"),
("DIM_OFFICE","People & Relationships","Office","BBH offices, used to roll figures up by location.","one row per office","high"),
("REF_OFFICER_CONTACTS","People & Relationships","Officer Contacts","Which officer covers which account or relationship.","one row per officer to account assignment","high"),
("REF_BRANCH","People & Relationships","Branch","The branch codes used across accounts and reporting, and the branch each one names.","one row per branch","high"),
("DIM_CRM_DW_CONTACTS","People & Relationships","CRM Contacts","Contacts as the CRM holds them, brought across so warehouse reporting agrees with the CRM.","one row per CRM contact","high"),
("DIM_CRM_TAR_CONTACTS","People & Relationships","CRM TAR Contacts","A second CRM contact set. TAR is not expanded anywhere in the lineage — confirm what it stands for.","one row per contact","low"),
("DIM_CRM_EMPLOYEE_OFFICES","People & Relationships","CRM Employee Offices","Which office each employee works from, as the CRM records it.","one row per employee per office","high"),
("DIM_CRM_ACCOUNT_ONLINE_ACCESS","People & Relationships","Online Access","Who has online access to which account, and at what level.","one row per account per user","high"),
("DIM_CRM_OB_REQUEST","People & Relationships","Onboarding Requests","Requests raised to onboard a client or account, and where each one has got to.","one row per onboarding request","med"),
("DIM_CRM_REQUEST_AUTHORIZER","People & Relationships","Request Authorisers","Who is entitled to approve each kind of request.","one row per request per authoriser","high"),

# ---- Holdings & Positions ----------------------------------------------
("FACT_CP_HOLDINGS","Holdings & Positions","Holdings","What each account holds, by security, with quantity and value. The figure most client reporting starts from.","one row per account per security per day","high"),
("FACT_CP_HOLDINGS_TEMP","Holdings & Positions","Holdings — Staging","The holdings load in progress. Not a reporting table.","one row per account per security, current batch","high"),
("FACT_HOLDINGS_BATCH","Holdings & Positions","Holdings Batch","Which holdings load produced which figures, so a number can be traced to a run.","one row per holdings batch","high"),
("FACT_HOLDINGS_UPDATED","Holdings & Positions","Holdings Changed Today","Holdings that moved in the latest run, so downstream processes need only look at what changed.","one row per changed holding per run","high"),
("FACT_TAX_LOT","Holdings & Positions","Tax Lots","Each separately acquired parcel of a holding, with its cost and acquisition date — what gain and loss is calculated from.","one row per tax lot","high"),
("FACT_TAX_LOT_HIST","Holdings & Positions","Tax Lots — History","Previous states of those parcels, so a restatement can be traced.","one row per tax lot per change","high"),
("FACT_CRD_TAX_LOT","Holdings & Positions","Tax Lots (Charles River)","Tax lots as the Charles River order management system holds them, for comparison with BBH's own.","one row per tax lot in Charles River","high"),
("FACT_CP_URGL_GRAPH","Holdings & Positions","Unrealised Gain & Loss Trend","Unrealised gain and loss over time, shaped for the chart that shows it.","one row per account per period","med"),
("FACT_PLEDGE","Holdings & Positions","Pledged Assets","Holdings pledged as collateral and therefore not freely available.","one row per pledge","high"),
("FACT_STAR_PORTFOLIO_VALUATION","Holdings & Positions","Portfolio Valuation (STAR)","The nightly portfolio valuation delivered by STAR.","one row per account per security per valuation date","high"),

# ---- Transactions & Cash -----------------------------------------------
("FACT_TRANSACTIONS","Transactions & Cash","Transactions","Every posting against an account — purchases, sales, income, fees, transfers.","one row per transaction","high"),
("FACT_TRADES","Transactions & Cash","Trades","Buy and sell orders and how they were executed.","one row per trade","high"),
("FACT_CASH_SETTLEMENTS","Transactions & Cash","Cash Settlements","Cash movements settling against trades and other activity.","one row per settlement","high"),
("FACT_CASH_PROJECTION","Transactions & Cash","Projected Cash","Cash expected in and out on future dates, so an account's forward position is visible.","one row per account per future date","high"),
("FACT_CHECK_REGISTER","Transactions & Cash","Check Register","Cheques issued against accounts and their status.","one row per cheque","high"),
("FACT_REGISTER_BALANCE","Transactions & Cash","Register Balance","The running balance the register reconciles to.","one row per account per date","med"),
("FACT_DIV_INT_TEMP","Transactions & Cash","Dividends & Interest — Staging","Dividend and interest postings in progress. Not a reporting table.","one row per posting, current batch","high"),
("REF_TRANSACTION_CODE","Transactions & Cash","Transaction Codes","What each transaction code means, so a posting can be read without a lookup sheet.","one row per transaction code","high"),
("REF_DISBURSEMENT_CODE","Transactions & Cash","Disbursement Codes","What each disbursement code means.","one row per disbursement code","high"),
("FACT_PENNY_IT","Transactions & Cash","Penny Test Items","Small-value verification items. IT is not expanded anywhere in the lineage — confirm before publishing.","one row per item","low"),

# ---- Securities & Pricing ----------------------------------------------
("DIM_SECURITY","Securities & Pricing","Security","Every instrument BBH can hold, with its identifiers and characteristics.","one row per security","high"),
("DIM_SECURITY_UD","Securities & Pricing","Security User-Defined Fields","Extra attributes the business records against a security.","one row per security per field","high"),
("DIM_SECURITY_UD_HIST","Securities & Pricing","Security User-Defined Fields — History","Previous values of those security attributes.","one row per security per field per change","high"),
("REF_SECURITY_TYPE","Securities & Pricing","Security Types","The instrument-type classification used throughout the warehouse.","one row per security type","high"),
("REF_ISSUER","Securities & Pricing","Issuer","Who issued each security, used for issuer concentration and credit views.","one row per issuer","high"),
("REF_SM_SECURITY","Securities & Pricing","Security Master Extract","Security attributes from the security master. SM is not expanded anywhere in the lineage.","one row per security","low"),
("PBDW_CSM_SECURITY","Securities & Pricing","Compliance Security Master","Security attributes as the compliance system holds them. CSM is not expanded anywhere in the lineage.","one row per security","low"),
("FACT_PRICE","Securities & Pricing","Price","The price used to value each security on each day.","one row per security per date","high"),
("FACT_PRICE_FIS","Securities & Pricing","Price (FIS)","Prices as delivered by FIS, before any vendor is chosen.","one row per security per date","high"),
("FACT_PRICE_TR","Securities & Pricing","Price (Thomson Reuters)","Prices as delivered by Thomson Reuters, before any vendor is chosen.","one row per security per date","med"),
("FACT_PRICE_REALTIME","Securities & Pricing","Price — Intraday","Prices refreshed during the day rather than at close.","one row per security per intraday snapshot","high"),
("TEMP_PRICE_CHANGE","Securities & Pricing","Price Change — Staging","Prices that moved in the current run. Not a reporting table.","one row per security, current run","high"),
("TEMP_PRICE_CHANGE_YESTERDAY","Securities & Pricing","Price Change — Previous Run","The prior run's price movements, kept for comparison.","one row per security, previous run","high"),
("FACT_SECURITY_MEASURES","Securities & Pricing","Security Measures","Calculated measures on a security — yield, duration and the like.","one row per security per measure per date","high"),
("FACT_SECURITY_MEASURES_HIST","Securities & Pricing","Security Measures — History","Previous values of those measures.","one row per security per measure per date","high"),
("FACT_MBS_FACTOR","Securities & Pricing","Mortgage-Backed Security Factors","The paydown factor for each mortgage-backed security, which determines the outstanding balance.","one row per security per factor date","high"),
("CFG_SECURITY_TYPE_CHANGE","Securities & Pricing","Security Type Reclassifications","Securities whose type has been reclassified, and from what to what.","one row per reclassification","high"),
("CFG_TR_CUSIP_LTS","Securities & Pricing","Thomson Reuters CUSIP List","A controlled list of CUSIPs for Thomson Reuters processing. LTS is not expanded anywhere in the lineage.","one row per CUSIP","low"),

# ---- Investment Policy --------------------------------------------------
("DIM_BBH_IPS","Investment Policy","Investment Policy Statement","The agreed investment policy for a relationship — what the portfolio is meant to do.","one row per policy statement","high"),
("DIM_BBH_IPS_HISTORY","Investment Policy","Investment Policy — History","Previous versions of each policy, so a change of mandate is traceable.","one row per policy per version","high"),
("DIM_BBH_IPS_APPROVAL","Investment Policy","Policy Approvals","Whether each policy has been approved, and when.","one row per policy per approval","high"),
("DIM_BBH_IPS_APPROVER","Investment Policy","Policy Approvers","Who may approve a policy, so an approval can be checked against an entitlement.","one row per approver","high"),
("DIM_BBH_IPS_ASSET","Investment Policy","Policy Asset Classes","The asset classes a policy covers and the weight agreed for each.","one row per policy per asset class","high"),
("DIM_BBH_IPS_SUBASSET_CLASS","Investment Policy","Policy Sub-Asset Classes","The finer breakdown beneath each asset class.","one row per policy per sub-asset class","high"),
("DIM_BBH_IPS_INVESTOR_PROFILE","Investment Policy","Investor Profile","The client's objectives, risk tolerance and constraints as recorded on the policy.","one row per policy","high"),
("DIM_BBH_IPS_TRANSLATION","Investment Policy","Policy Translations","Policy wording in each language it is issued in.","one row per policy per language","high"),
("DIM_BBH_IPS_WS","Investment Policy","Policy Worksheet","The working version of a policy while it is being drafted.","one row per worksheet","high"),
("DIM_BBH_IPS_WS_OPTOUT","Investment Policy","Policy Worksheet Opt-Outs","Parts of the policy the client has declined, recorded on the worksheet.","one row per worksheet per opt-out","high"),
("DIM_BBH_IPS_UIMP","Investment Policy","Policy UIMP","A policy structure abbreviated UIMP. UIMP is not expanded anywhere in the lineage — this one needs an owner to name it.","one row per policy per UIMP entry","low"),
("DIM_BBH_IPS_UIMP_REALLOCATION","Investment Policy","Policy UIMP Reallocation","Reallocations against those UIMP entries. UIMP is not expanded anywhere in the lineage — confirm before publishing.","one row per reallocation","low"),
("DIM_IPS_CONSOLIDATED","Investment Policy","Consolidated Policy View","One policy view across the accounts a relationship holds.","one row per relationship","high"),
("DIM_IPS_DETAILS","Investment Policy","Policy Details","The detailed lines of a policy.","one row per policy per detail line","high"),
("DIM_IPS_ACCOUNTS_RELATION","Investment Policy","Policy Accounts","Which accounts each policy governs.","one row per policy per account","high"),
("DIM_IPS_OPT_OUTS","Investment Policy","Policy Opt-Outs","Parts of the agreed policy the client has declined.","one row per policy per opt-out","high"),
("DIM_IPS_SPL_CONSIDERATIONS","Investment Policy","Special Considerations","Client-specific instructions and restrictions that sit outside the standard policy.","one row per policy per consideration","high"),
("REF_IPS_OBJECTIVE","Investment Policy","Investment Objectives","The objectives a policy can be set to.","one row per objective","high"),
("DIM_BBH_ASSET_ALLOCATIONS","Investment Policy","Target Asset Allocation","The target weights a portfolio is managed to.","one row per allocation model per asset class","high"),
("DIM_BBH_ASSET_THRESHOLD","Investment Policy","Allocation Thresholds","How far a holding may drift from target before it is flagged.","one row per asset class per threshold","high"),
("REF_ACTIVE_BLEND_ALLOCATION","Investment Policy","Active Blend Allocation","The blend of active and passive management applied to an allocation.","one row per blend per asset class","med"),
("REF_ASSET_CLASS","Investment Policy","Asset Classes","The asset-class scheme used across allocation and reporting.","one row per asset class","high"),

# ---- Performance & Benchmarks ------------------------------------------
("FACT_FR_PERFORMANCE","Performance & Benchmarks","Performance Returns","Returns for each account and period — what the portfolio actually did.","one row per account per period","high"),
("FACT_FR_PERFORMANCE_TAB1","Performance & Benchmarks","Performance — Report Section 1","Performance figures arranged for the first section of the client report.","one row per account per period","med"),
("FACT_FR_PERFORMANCE_TAB2","Performance & Benchmarks","Performance — Report Section 2","Performance figures arranged for the second section of the client report.","one row per account per period","med"),
("FACT_FR_PERFORMANCE_TAB3","Performance & Benchmarks","Performance — Report Section 3","Performance figures arranged for the third section of the client report.","one row per account per period","med"),
("FACT_FR_BENCHMARK","Performance & Benchmarks","Benchmark Returns","Returns for each benchmark, which portfolio performance is measured against.","one row per benchmark per period","high"),
("FACT_FR_BENCHMARK_TAB1","Performance & Benchmarks","Benchmark — Report Section 1","Benchmark figures arranged for the first section of the client report.","one row per benchmark per period","med"),
("FACT_FR_BENCHMARK_TAB2","Performance & Benchmarks","Benchmark — Report Section 2","Benchmark figures arranged for the second section of the client report.","one row per benchmark per period","med"),
("FACT_FR_BENCHMARK_TAB3","Performance & Benchmarks","Benchmark — Report Section 3","Benchmark figures arranged for the third section of the client report.","one row per benchmark per period","med"),
("REF_BENCHMARK_DESC","Performance & Benchmarks","Benchmark Descriptions","What each benchmark is and what it represents.","one row per benchmark","high"),
("REF_BENCHMARK_MAPPING","Performance & Benchmarks","Benchmark Assignment","Which benchmark each account or asset class is measured against.","one row per account or asset class per benchmark","high"),
("REF_FR_BENCHMARK_APPROVAL","Performance & Benchmarks","Benchmark Approvals","Whether a benchmark assignment has been approved for use in client reporting.","one row per benchmark assignment per approval","high"),
("REF_FR_RISK_FREE_RATE","Performance & Benchmarks","Risk-Free Rate","The rate used as the risk-free baseline in risk-adjusted return measures.","one row per date","high"),
("REF_FR_SECTOR_ROLLUP","Performance & Benchmarks","Sector Roll-Up","How detailed sectors combine into the sectors shown on a report.","one row per detailed sector","high"),
("REF_FR_ASCT_SECTOR_MAPPING","Performance & Benchmarks","Asset Class to Sector Mapping","How asset classes map onto reporting sectors.","one row per asset class per sector","med"),
("REF_FR_ASSET_CLASS_MAPPING","Performance & Benchmarks","Performance Asset Class Mapping","How holdings map onto the asset classes performance is reported by.","one row per holding classification","high"),
("REF_FR_ASSET_SCHEMA","Performance & Benchmarks","Performance Asset Schema","The classification scheme performance reporting is built on.","one row per schema entry","med"),
("FR_PERFORMANCE_FILE_ENTRY","Performance & Benchmarks","Performance File Load","Each performance file received, and whether it loaded.","one row per file received","high"),
("FR_BENCHMARK_FILE_ENTRY","Performance & Benchmarks","Benchmark File Load","Each benchmark file received, and whether it loaded.","one row per file received","high"),
("FR_BEN_COUNT","Performance & Benchmarks","Benchmark Load Count","Row counts from the benchmark load, used to check a file arrived whole.","one row per load","high"),
("FRCOUNT","Performance & Benchmarks","Performance Load Count","Row counts from the performance load, used to check a file arrived whole.","one row per load","med"),

# ---- Fees & Billing -----------------------------------------------------
("FACT_FEE_ACCOUNT_WORKSHEET","Fees & Billing","Fee Worksheet","The calculation behind each account's fee for a billing period.","one row per account per billing period","high"),
("FACT_FEE_ACCT_WKSHEET_AMOUNTS","Fees & Billing","Fee Worksheet Amounts","The amounts making up each fee calculation.","one row per worksheet per amount","high"),
("FACT_FEE_ACCT_WKSHEET_ALLOC","Fees & Billing","Fee Allocation","How a fee is split across the accounts that bear it.","one row per worksheet per account share","high"),
("FACT_FEE_ACCT_WKSHT_COMPONENT","Fees & Billing","Fee Components","The separate charges a fee is built from.","one row per worksheet per component","high"),
("FACT_FEE_ACCT_WKSHT_COMP_STEPS","Fees & Billing","Fee Tier Steps","The tiered rate steps applied within a fee component.","one row per component per tier","high"),
("FACT_FEE_MA_ACCT_WKSHT_CENT_AC","Fees & Billing","Master Account Central Billing","Fees billed centrally at master-account level rather than to each account.","one row per master account per billing period","med"),
("FACT_FEE_RECEIVE_OPEN","Fees & Billing","Fees Outstanding","Fees billed and not yet received.","one row per open fee receivable","high"),
("REF_FEE_RECEIVE_BALANCE","Fees & Billing","Fee Receivable Balance","The outstanding fee balance per account.","one row per account","high"),
("REF_FEE_RECEIVE_MSTR_BALANCE","Fees & Billing","Fee Receivable Balance — Master Account","The outstanding fee balance rolled up to master account.","one row per master account","high"),
("REF_FEE_SCHEDULE","Fees & Billing","Fee Schedules","The fee schedules an account can be billed on.","one row per fee schedule","high"),
("REF_FEE_SCHEDULE_COMPONENT","Fees & Billing","Fee Schedule Components","The charges each schedule is made up of.","one row per schedule per component","high"),
("REF_FEE_SCHEDULE_DETAILS","Fees & Billing","Fee Schedule Details","The rates and tiers within each schedule.","one row per schedule per rate line","high"),
("REF_FIS_FEE_SCHEDULE","Fees & Billing","Fee Schedules (FIS)","Fee schedules as FIS holds them, for comparison with BBH's own.","one row per fee schedule in FIS","high"),

# ---- Assets Under Management -------------------------------------------
("FACT_AUM","Assets Under Management","Assets Under Management","The value of assets BBH manages or administers, by account and period.","one row per account per period","high"),
("FACT_NET_FLOW_AUM","Assets Under Management","Net Flows","Money in and out, separated from market movement, so growth can be explained.","one row per account per period","high"),
("FACT_MONTHLY_FEES_AUM","Assets Under Management","Fees Against AUM","Monthly fees set against the assets they were charged on.","one row per account per month","high"),
("FACT_ACCOUNT_SUMMARY","Assets Under Management","Account Summary","One summary line per account per period — the figures most reports open with.","one row per account per period","high"),
("RPT_SIGNIFICANT_FUNDS","Assets Under Management","Significant Funds","Funds large enough to need separate oversight.","one row per fund per period","med"),

# ---- Statements & Reporting --------------------------------------------
("FACT_STATEMENT_HOLDING","Statements & Reporting","Statement Holdings","Holdings exactly as they were printed on a client statement.","one row per statement per holding","high"),
("FACT_STATEMENT_CASH","Statements & Reporting","Statement Cash","Cash activity exactly as it was printed on a client statement.","one row per statement per cash line","high"),
("FACT_STMT_TRANSACTIONS","Statements & Reporting","Statement Transactions","Transactions exactly as they were printed on a client statement.","one row per statement per transaction","high"),
("FACT_STATEMENT_STATUS","Statements & Reporting","Statement Status","Whether each statement has been produced, held or sent.","one row per statement","high"),
("PBDW_REPORT_CONFIGURATION","Statements & Reporting","Report Configuration","Which reports run, for whom, and with what options.","one row per report configuration","high"),
("FACT_MAP_HEADER","Statements & Reporting","MAP Report Header","The header of a MAP report. MAP is not expanded anywhere in the lineage — confirm before publishing.","one row per report","low"),
("FACT_MAP_DETAILS","Statements & Reporting","MAP Report Details","The detail lines of a MAP report. MAP is not expanded anywhere in the lineage — confirm before publishing.","one row per report per line","low"),

# ---- Compliance & Oversight --------------------------------------------
("CRD_COMPL_RULES","Compliance & Oversight","Compliance Rules (Charles River)","The investment restrictions each portfolio is tested against.","one row per rule","high"),
("PBDW_CS_TEST_V2","Compliance & Oversight","Compliance Tests","Each compliance test run, and against what.","one row per test run","med"),
("PBDW_CS_VIOLATIONS_V2","Compliance & Oversight","Compliance Violations","Tests that failed — a portfolio outside its restrictions.","one row per violation","med"),
("REF_ACCOUNT_REVIEW_RECON","Compliance & Oversight","Account Review Reconciliation","Accounts due for periodic review and whether the review happened.","one row per account per review cycle","high"),
("REF_MASTER_REVIEW_RECON","Compliance & Oversight","Master Account Review Reconciliation","The same review check at master-account level.","one row per master account per review cycle","high"),
("TMP_ALERTS","Compliance & Oversight","Alerts — Staging","Alerts raised by the current run. Not a reporting table.","one row per alert, current run","high"),

# ---- Lending & Credit ---------------------------------------------------
("REF_ACBS_FACILITY_LIST","Lending & Credit","Credit Facilities","Lending facilities extended to clients, from the ACBS commercial lending system.","one row per facility","high"),
("REF_ACBS_KEY_METRICS","Lending & Credit","Credit Facility Metrics","Balances, limits and utilisation on each facility.","one row per facility per metric date","high"),
("REF_ACBS_SYND_PARTICIPATION","Lending & Credit","Syndicated Loan Participation","BBH's share of loans syndicated across several lenders.","one row per facility per participant","high"),

# ---- Tax ----------------------------------------------------------------
("REF_TRUST_TAX","Tax","Trust Tax","Tax attributes of trust accounts, used for withholding and filing.","one row per account","high"),
("REF_K1_DETAIL","Tax","Schedule K-1 Detail","Partnership income detail reported to investors on a Schedule K-1.","one row per partner per tax year","high"),

# ---- Market & Fund Research --------------------------------------------
("REF_IRG_FUND_DETAILS","Market & Fund Research","Fund Details","Fund characteristics from the investment research group's data set.","one row per fund","med"),
("REF_IRG_FUND_RETURNS","Market & Fund Research","Fund Returns","Published returns for each fund.","one row per fund per period","med"),
("REF_IRG_FUND_FACTOR","Market & Fund Research","Fund Factors","Factor exposures attributed to each fund.","one row per fund per factor","med"),
("REF_IRG_MORNING_STAR","Market & Fund Research","Morningstar Data","Fund data as supplied by Morningstar.","one row per fund","high"),
("REF_IRG_SECTOR_NAMES","Market & Fund Research","Research Sector Names","The sector names used in research data.","one row per sector","med"),
("REF_IRG_SP500_INFO","Market & Fund Research","S&P 500 Constituents","S&P 500 index membership and attributes.","one row per constituent","high"),
("REF_PRIVATE_MARKET_FUND","Market & Fund Research","Private Market Funds","Private equity, credit and real asset funds clients are invested in.","one row per fund","high"),

# ---- Shared Reference ---------------------------------------------------
("REF_CODE_DESC","Shared Reference","Code Descriptions","The general lookup: what every short code in the warehouse means.","one row per code set per code","high"),
("REF_BANK_NAME","Shared Reference","Bank Names","Banks referenced by accounts and instructions.","one row per bank","high"),
("REF_INSTITUTION_CODE","Shared Reference","Institution Codes","Financial institutions and their identifying codes.","one row per institution","high"),
("REF_CRD_BRANCHCODE","Shared Reference","Branch Codes (Charles River)","Branch codes as Charles River uses them, mapped to BBH branches.","one row per branch code","high"),
("REF_ADDV_TAB_35","Shared Reference","AddVantage Table 35","An AddVantage lookup carried across under its source table number. TAB_35 is not expanded anywhere in the lineage — it needs a business name and an owner.","one row per code","low"),
("DIM_DATE","Shared Reference","Calendar","The date dimension every periodic report joins to.","one row per date","high"),
("DIM_CONTROL_DATES","Shared Reference","Processing Dates","The business dates each process runs for, which decide what 'today' means to a report.","one row per process per date","high"),

# ---- Change History -----------------------------------------------------
("AUDIT_TRAIL_ACCOUNT","Change History","Account Changes","Who changed what on an account, and when.","one row per account change","high"),
("AUDIT_TRAIL_MASTER_ACCOUNT","Change History","Master Account Changes","Who changed what on a master account, and when.","one row per master account change","high"),
("AUDIT_TRAIL_INTERESTED_PARTY","Change History","Party Changes","Who changed what on an interested party, and when.","one row per party change","high"),
("AUDIT_TRAIL_IP_RELATIONSHIP","Change History","Relationship Changes","Who changed a party's relationship to an account, and when.","one row per relationship change","high"),
("AUDIT_TRAIL_SECURITY","Change History","Security Changes","Who changed what on a security, and when.","one row per security change","high"),

# ---- Platform & Operations ----------------------------------------------
("PBDW_ETL_AUDIT_LOG","Platform & Operations","Load Log","Every warehouse load: when it ran, how long it took, and whether it succeeded.","one row per load step per run","high"),
("API_INTRADAY_KEYS","Platform & Operations","Intraday API Keys","Keys the intraday API uses to identify what to refresh.","one row per key","med"),
("CFG_BACK_DATED_LIST","Platform & Operations","Back-Dated Processing List","Accounts approved for back-dated processing.","one row per account","high"),
("CFG_BACK_DATED_LIST_HIST","Platform & Operations","Back-Dated Processing List — History","Previous versions of that list.","one row per account per change","high"),
("CFG_BACK_DATED_LIST_TEMP","Platform & Operations","Back-Dated Processing List — Staging","The list being assembled by the current run.","one row per account, current run","high"),
("TWM001_USER_REF","Platform & Operations","User Reference (TWM001)","A user reference table carried across under its source system name. TWM001 is not expanded anywhere in the lineage — confirm what it stands for.","one row per user","low"),
]
