#!/usr/bin/env python3
"""Discovery before ingestion: every sheet, header row, column and row
count of the two UD workbooks and the extract's header, written to
docs/advantage_ud/source_inventory.md. A column the brief does not describe
is listed UNDOCUMENTED, never guessed at.

    python tools/advantage_ud_discovery.py [local-data/advantage-ud]

Structure only: no cell value is written, only headers and counts.
"""
from __future__ import annotations

import csv
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

from ingestion.advantage_ud_workbook_conn import (find_header_row, DOCUMENTED_LIST,   # noqa: E402
                                                  DOCUMENTED_TABLES, is_trp_header)

EXTRACT_COLS = ["ACCOUNT_NUMBER", "AS_OF_DATE", "USER_DEFINED_ATTRIBUTE_CLOB", "LOAD_DATE", "BATCH_ID",
                "LOAD_TYPE", "FIS_LOAD_DATE", "ACTIVE_IND", "ACCOUNT_UD_KEY", "ACCOUNT_KEY",
                "CREATED_TSP", "UPDATED_TSP"]


def inventory(folder):
    lines = ["# AddVantage UD sources: inventory", "",
             "Generated by `tools/advantage_ud_discovery.py`. Structure only: sheet names,",
             "header rows, column names and counts. No cell value appears here.", ""]
    found = False
    for name in sorted(os.listdir(folder)):
        p = os.path.join(folder, name)
        low = name.lower()
        if low.endswith(".csv") and "datavar" in low:
            found = True
            with open(p, newline="", encoding="utf-8-sig") as fh:
                rd = csv.reader(fh)
                hdr = [h.strip().upper() for h in next(rd)]
                n = sum(1 for _ in rd)
            lines += [f"## `{name}` (extract)", "", f"- rows: {n:,} data rows + 1 header", f"- columns: {len(hdr)}", ""]
            for h in hdr:
                lines.append(f"- `{h}`" + ("" if h in EXTRACT_COLS else "  UNDOCUMENTED"))
            missing = [c for c in EXTRACT_COLS if c not in hdr]
            if missing:
                lines.append(f"- MISSING from the brief's contract: {', '.join(missing)}")
            lines.append("")
        elif low.endswith((".xlsx", ".xlsm")):
            found = True
            from openpyxl import load_workbook
            wb = load_workbook(p, read_only=True, data_only=True)
            kind = "TRP samples" if "trp" in low else "UD workbook" if "user defined" in low or "addv" in low else "workbook"
            lines += [f"## `{name}` ({kind})", ""]
            for ws in wb.worksheets:
                hr, hdr = find_header_row(ws)
                rows = max(0, (ws.max_row or 0) - hr)
                lines += [f"### sheet `{ws.title}`", "", f"- header row: {hr}", f"- columns: {len(hdr)}", f"- rows below header: {rows:,}", ""]
                doc = DOCUMENTED_LIST if ws.title.lower() == "list" else DOCUMENTED_TABLES if ws.title.lower() == "tables" else None
                for h in hdr:
                    if not h:
                        continue
                    if kind == "TRP samples":
                        tag = "" if (is_trp_header(h) or h.strip().lower() == "account number") else "  UNDOCUMENTED"
                    elif doc is not None:
                        tag = "" if h.strip().lower() in doc else "  UNDOCUMENTED"
                    else:
                        tag = "  UNDOCUMENTED (sheet not described by the brief)"
                    lines.append(f"- `{h}`{tag}")
                lines.append("")
    if not found:
        lines.append("_No workbook or extract found in the folder._")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    folder = sys.argv[1] if len(sys.argv) > 1 else os.path.join("local-data", "advantage-ud")
    out = os.path.join("docs", "advantage_ud", "source_inventory.md")
    text = inventory(folder)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(text)
    print(f"written: {out}")
